projects/sbb-esta/angular-business/src/lib/field/field.ts, projects/sbb-esta/angular-business/src/public-api.ts, projects/sbb-esta/angular-public/src/lib/field/styles/_formerror.scss, projects/sbb-esta/angular-public/src/lib/field/styles/_input-field.scss, projects/sbb-esta/angular-public/src/public-api.ts, projects/sbb-esta/angular-public/src/styles/common/_form.scss
Exposes the field component for business applications. This also changes the styling of the form labels.
Styling is according to the [digital guidelines of SBB for business applications](https://digital.sbb.ch/en/webapps).
=> feat(business/field): expose field component for business

projects/sbb-esta/angular-public/src/lib/datepicker/datepicker/datepicker.component.ts
=> fix(datepicker): fixes arrows change detection on manual change

projects/sbb-esta/angular-public/src/styles/typography/_table.scss
=> fix(table): fixes even row styling

projects/angular-showcase/src/app/getting-started/getting-started.md, projects/angular-showcase/src/docs/markdown/sbb-angular-getting-started.html, projects/sbb-esta/angular-public/src/lib/datepicker/calendar/calendar-header.component.html, projects/sbb-esta/angular-public/src/lib/datepicker/datepicker-toggle/datepicker-toggle.component.html, projects/sbb-esta/angular-public/src/lib/datepicker/month-view/month-view.component.html, projects/sbb-esta/angular-public/src/lib/file-selector/file-selector/file-selector.component.html, projects/sbb-esta/angular-public/src/lib/ghettobox/ghettobox/ghettobox.component.html, projects/sbb-esta/angular-public/src/lib/tabs/tabs/tabs.component.html, projects/sbb-esta/angular-public/src/lib/tag/tag/tag.component.html, projects/sbb-esta/angular-public/src/lib/tag/tags/tags.component.html, projects/sbb-esta/angular-public/src/lib/textarea/textarea/textarea.component.html, projects/sbb-esta/angular-public/src/lib/textexpand/textexpand/textexpand.component.html, projects/sbb-esta/angular-public/src/lib/usermenu/usermenu/usermenu.component.html, projects/sbb-esta/angular-public/tslint.json
All i18n attributes now have an id with the pattern sbbComponent... Also
added descriptions to all i18n attributes.
BREAKING CHANGE: i18n ids have changed.
=> feat(i18n): applies common pattern for i18n ids

projects/sbb-esta/angular-public/src/lib/_common/testing/type-in-element.ts, projects/sbb-esta/angular-public/src/lib/textarea/textarea/textarea.component.html, projects/sbb-esta/angular-public/src/lib/textarea/textarea/textarea.component.spec.ts, projects/sbb-esta/angular-public/src/lib/textarea/textarea/textarea.component.ts
=> fix(textarea): fix textarea update issue

projects/sbb-esta/angular-public/src/styles/typography/_table.scss
=> fix(table): fix align helper classes for .sbb-table

projects/sbb-esta/angular-public/src/lib/ghettobox/styles/_ghettobox-base.scss
Make ghetto box icons independent of outer line-height definition
=> Ghetto box icons

projects/sbb-esta/angular-public/src/lib/file-selector/file-selector/file-selector.component.spec.ts, projects/sbb-esta/angular-public/src/lib/file-selector/file-selector/file-selector.component.ts
The test has been done on the changeDetector event. This will make sure that angular will detect any changes made also during the same cycle.
=> fix(file-selector): fix upload with two way binding update (#115)

projects/angular-showcase/src/app/public/examples/autocomplete-showcase/autocomplete-showcase.component.html, projects/angular-showcase/src/app/public/examples/autocomplete-showcase/autocomplete-showcase.component.ts, projects/sbb-esta/angular-public/autocomplete/autocomplete.md, projects/sbb-esta/angular-public/autocomplete/src/autocomplete-hint/autocomplete-hint.component.html, projects/sbb-esta/angular-public/autocomplete/src/autocomplete-hint/autocomplete-hint.component.scss, projects/sbb-esta/angular-public/autocomplete/src/autocomplete-hint/autocomplete-hint.component.ts, projects/sbb-esta/angular-public/autocomplete/src/autocomplete.module.ts, projects/sbb-esta/angular-public/autocomplete/src/public_api.ts
Autocomplete options list can be enhanced with additional text.
New feature implementation according #154
=> feat(autocomplete): implement autocomplete hint

angular.json, projects/angular-showcase/src/app/app.component.html, projects/angular-showcase/src/app/app.module.ts, projects/angular-showcase/src/app/business/business.module.ts, projects/angular-showcase/src/app/core/core.module.ts, projects/angular-showcase/src/app/core/core/core.component.ts, projects/angular-showcase/src/app/icons/icons.module.ts, projects/angular-showcase/src/app/public/public.module.ts, projects/angular-showcase/src/app/shared/shared.module.ts, projects/sbb-esta/angular-core/ng-package.json, projects/sbb-esta/angular-core/package.json, projects/sbb-esta/angular-core/public-api.ts, projects/sbb-esta/angular-core/scrolling/index.ts, projects/sbb-esta/angular-core/scrolling/package.json, projects/sbb-esta/angular-core/scrolling/scrolling.md, projects/sbb-esta/angular-core/scrolling/src/ps-scrollable.directive.spec.ts, projects/sbb-esta/angular-core/scrolling/src/ps-scrollable.directive.ts, projects/sbb-esta/angular-core/scrolling/src/public_api.ts, projects/sbb-esta/angular-core/scrolling/src/scrolling.module.ts, projects/sbb-esta/angular-public/lightbox/src/lightbox.module.ts, projects/sbb-esta/angular-public/lightbox/src/lightbox/lightbox.spec.ts, projects/sbb-esta/angular-public/select/src/select.module.ts, projects/sbb-esta/angular-public/select/src/select/select.component.spec.ts, projects/sbb-esta/angular-public/tabs/src/tabs.module.ts, projects/sbb-esta/angular-public/tabs/src/tabs/tabs.component.spec.ts
=> fix: handle scrolling correctly

CONTRIBUTING.md, projects/sbb-esta/angular-business/header/src/header/header.component.html, projects/sbb-esta/angular-business/header/src/header/header.component.scss
This resolves the following problems with the header:
1. use a custom component for the user menu (e.g. which wraps the sbb-usermenu)
2. add additional components to the header (e.g. auto save feedback icons)
=> Enhancements custom components for header

.travis.yml, projects/sbb-esta/angular-public/autocomplete/src/autocomplete/autocomplete-trigger.directive.ts, projects/sbb-esta/angular-public/option/src/option/highlight.pipe.ts, projects/sbb-esta/angular-public/option/src/option/option.component.ts, projects/sbb-esta/angular-public/search/src/search/search.component.ts
=> fix: autocomplete freezes on backspacing

projects/sbb-esta/angular-public/radio-button-panel/src/radio-button-panel/radio-button-panel.component.html, projects/sbb-esta/angular-public/radio-button-panel/src/radio-button-panel/radio-button-panel.component.spec.ts, projects/sbb-esta/angular-public/radio-button-panel/src/radio-button-panel/radio-button-panel.component.ts, projects/sbb-esta/angular-public/radio-button/src/radio-button/radio-button-registry.service.ts, projects/sbb-esta/angular-public/radio-button/src/radio-button/radio-button.component.html, projects/sbb-esta/angular-public/radio-button/src/radio-button/radio-button.component.spec.ts, projects/sbb-esta/angular-public/radio-button/src/radio-button/radio-button.component.ts, projects/sbb-esta/angular-public/radio-button/src/radio-button/radio-button.interface.ts, projects/sbb-esta/angular-public/radio-button/src/radio-button/radio-button.model.ts, projects/sbb-esta/angular-public/toggle/src/toggle-option/toggle-option.component.html, projects/sbb-esta/angular-public/toggle/src/toggle-option/toggle-option.component.ts, projects/sbb-esta/angular-public/toggle/src/toggle/toggle.component.ts
=> fix: normalize radio button behavior

projects/angular-showcase/src/app/business/business-examples/business-examples.module.ts, projects/angular-showcase/src/app/business/business-examples/usermenu-showcase/usermenu-showcase.component.html, projects/angular-showcase/src/app/business/business-examples/usermenu-showcase/usermenu-showcase.component.ts, projects/angular-showcase/src/app/business/business/business.component.ts, projects/angular-showcase/src/app/public/public-examples/usermenu-showcase/usermenu-showcase.component.html, projects/sbb-esta/angular-public/usermenu/src/_usermenu.scss
feat(usermenu): style business usermenu and add examples
Limit usermenu styling to not include 4k and 5k resolutions in business build and add showcase.
=> feat(business): adapt usermenu styling

projects/sbb-esta/angular-core/datetime/src/native-date-adapter.ts, projects/sbb-esta/angular-public/datepicker/src/date-input/date-input.directive.ts
Allow to customize usage of TitleCasePipe in DateInput/DatePicker by injecting it.
closes #226
=> fix(datepicker): configurable TitleCasePipe in DatePicker

projects/sbb-esta/angular-public/radio-button/src/_radio-button.scss
=> fix: fix the radio click with selected text

projects/sbb-esta/angular-core/styles/common/_checkbox.scss, projects/sbb-esta/angular-public/radio-button/src/_radio-button.scss
=> fix: set min size for radio button and checkbox icon

projects/sbb-esta/angular-public/select/src/styles/_select-base.scss
=> fix: on error display sbb-select with red color and border

projects/sbb-esta/angular-business/contextmenu/src/contextmenu/contextmenu.component.scss
=> fix(business): fix contextmenu stacking order and border issue

README.md
=> docs: browserstack

projects/sbb-esta/angular-business/header/src/header/header.component.scss
=> fix: limit header icon height to header height

projects/sbb-esta/angular-core/base/src/processflow-step-base.ts
=> fix: fix change detection for sbb-processflow-step title

projects/sbb-esta/angular-public/select/src/select/select.component.html, projects/sbb-esta/angular-public/select/src/select/select.component.spec.ts
=> fix: limit sbb-select dropdown width to host

CONTRIBUTING.md, projects/sbb-esta/angular-public/textarea/src/textarea/textarea.component.html, projects/sbb-esta/angular-public/textarea/src/textarea/textarea.component.ts
This PR fixes #217 and the other issue mentioned in #217.
=> fix(textarea): trigger calculation of remaining characters correctly

projects/sbb-esta/angular-core/styles/typography/_fonts.scss
=> fix: use the correct SBB fonts

angular.json
changeDetection: OnPush, viewEncapsulation: None
=> chore: set defaults for component generation

projects/sbb-esta/angular-business/header/src/header-menu-trigger/header-menu-trigger.component.scss
=> fix(business): fix overlapping header menus

projects/sbb-esta/angular-public/search/src/search/search.component.spec.ts, projects/sbb-esta/angular-public/search/src/search/search.component.ts
show searchbox after clicking on header trigger
=> fix(public): search in header mode

projects/sbb-esta/angular-maps/esri-web-map/esri-web-map.md, projects/sbb-esta/angular-maps/esri-web-scene/esri-web-scene.md
Fix parameter portalItemId in documentation of SbbEsriWebscene & SbbEsriWebMap
=> docs(maps): fix parameter name for angular-maps

projects/sbb-esta/angular-icons/src/lib/him-cus/icon-utilization-medium.module.ts
=> fix(icons): fix utilization medium fixed size

projects/sbb-esta/angular-public/usermenu/src/usermenu/usermenu.component.scss
=> fix: fix too small width of usermenu in IE11

projects/sbb-esta/angular-public/usermenu/src/usermenu/usermenu.component.scss
=> fix: enable click on arrow in usermenu panel

.gitignore, projects/angular-showcase/src/app/business/business-examples/breadcrumb-showcase/breadcrumb-showcase.component.html, projects/angular-showcase/src/app/business/business-examples/breadcrumb-showcase/breadcrumb-showcase.component.ts, projects/angular-showcase/src/app/business/business-examples/business-examples.module.ts, projects/angular-showcase/src/app/business/business/business.component.ts, projects/sbb-esta/angular-public/breadcrumb/src/styles/_breadcrumb-base.scss, projects/sbb-esta/angular-public/breadcrumb/src/styles/_breadcrumb-variables.scss, projects/sbb-esta/angular-public/breadcrumb/src/styles/_breadcrumb.scss, schematics/public2business/index.js, schematics/public2business/index.ts
add business styling for breadcrumb component
=> feat(business): apply breadcrumb business styling

src/angular-business/processflow/processflow/processflow.component.scss, src/angular-public/processflow/processflow/processflow.component.scss
=> fix: processflow steps should not shrink

src/angular-business/tooltip/BUILD.bazel, src/angular-business/tooltip/tooltip/tooltip-container.component.scss, src/angular-business/tooltip/tooltip/tooltip-container.component.ts, src/angular-business/tooltip/tooltip/tooltip.component.scss
=> fix(business): fix styling of tooltip directive

src/angular-business/processflow/processflow/processflow.component.scss, src/angular-public/processflow/processflow/processflow.component.scss
=> fix: correct processflow steps spacing

src/angular-business/contextmenu/contextmenu/contextmenu.component.scss, src/showcase/app/business/business-examples/contextmenu-examples/simple-contextmenu-example/simple-contextmenu-example.component.scss, src/showcase/app/business/business-examples/contextmenu-examples/simple-contextmenu-example/simple-contextmenu-example.component.ts
=> fix(business): fix borders of contextmenu

src/angular-core/styles/common/_overlay.scss, src/angular-public/dropdown/dropdown/dropdown.component.scss, src/angular-public/option/option/option.component.scss, src/angular-public/select/select/select.component.html, src/angular-public/select/select/select.component.scss, src/angular-public/select/select/select.component.spec.ts, src/angular-public/select/select/select.component.ts
=> fix: fix tabbing to and from sbb-select

src/angular-core/styles/common/_button.scss
=> fix(public): fix expanding of width on frameless button when hovering

src/angular-core/styles/includes/_checkbox.scss
=> fix(public): fix overflow on checkbox-panel and radio-button-panel

src/showcase/app/business/business-examples/table-examples/selectable-table-example/selectable-table-example.component.ts
better for copy and paste when using with filteredData
=> docs: let table selection example use filteredData instead of data

src/angular-business/header/header/header.component.scss
=> fix(business): allow header menu to scroll

src/angular-public/select/select/select.component.ts
=> fix: sbb-select dropdown should adapt to changing width

src/angular-core/styles/includes/_checkbox.scss, src/angular-public/checkbox-panel/checkbox-panel/checkbox-panel.component.html, src/angular-public/radio-button-panel/radio-button-panel/radio-button-panel.component.html
=> fix(public): correct checkbox panel styling

src/angular-public/processflow/processflow/processflow.component.html, src/angular-public/processflow/processflow/processflow.component.scss
=> fix: move processflow overflow style rules to nested element

src/showcase/app/introduction/introduction.component.html
We clarify on our landing page the difference between the @sbb-esta/angular-public and @sbb-esta/angular-business packages.
=> docs: clarify public vs business

src/angular-core/styles/includes/_button.scss, src/angular-public/file-selector/file-selector/file-selector.component.scss
=> fix: vertically center text in ghost button

src/angular-public/datepicker/_datepicker.scss, src/angular-public/datepicker/calendar-body/calendar-body.component.html, src/angular-public/datepicker/datepicker-content/datepicker-content.component.scss, src/angular-public/datepicker/datepicker-toggle/datepicker-toggle.component.html, src/angular-public/datepicker/datepicker/datepicker.component.scss, src/angular-public/datepicker/month-view/month-view.component.html
=> fix: correct datepicker styles

src/angular-public/tag/tag.md, src/angular-public/tag/tag/tag.component.ts, src/angular-public/tag/tags/tags.component.html, src/angular-public/tag/tags/tags.component.spec.ts, src/angular-public/tag/tags/tags.component.ts
=> fix(public): update tag state after all tag was clicked and provide total amount as input

src/angular-business/header/header-breakpoint.ts, src/angular-business/header/header-menu-trigger/header-menu-trigger.component.ts, src/angular-business/header/header-menu/header-menu.component.ts, src/angular-business/header/header/header.component.ts, src/angular-core/breakpoints/breakpoints.ts
We added additional breakpoints for mobile, tablet and desktop devices for orientations protrait or landscape or both.
=> feat(core): define device orientation breakpoints

src/showcase/app/business/business-examples/table-examples/filter-sort-paginator-table-example/filter-sort-paginator-table-example.component.html, src/showcase/app/business/business-examples/table-examples/grouped-columns-table-example/grouped-columns-table-example.component.html, src/showcase/app/business/business-examples/table-examples/grouped-rows-and-columns-table-example/grouped-rows-and-columns-table-example.component.html, src/showcase/app/business/business-examples/table-examples/paginator-table-example/paginator-table-example.component.html, src/showcase/app/business/business-examples/table-examples/simple-table-example/simple-table-example.component.html, src/showcase/app/business/business-examples/table-examples/sortable-table-example/sortable-table-example.component.html
=> refactor(showcase): remove obsolete attributes from table examples

src/angular-public/tabs/tab/tab.component.ts, src/angular-public/tabs/tabs/tabs.component.ts, src/showcase/styles.scss
=> fix: remove outline from tab content

src/angular-business/tooltip/tooltip/tooltip.component.scss, src/angular-public/tooltip/tooltip/tooltip.component.scss
=> fix(business): correct tooltip colors

src/angular-maps/core/esri-types/esri-types.service.ts, src/angular-maps/core/hit-test/hit-test.service.ts, src/angular-maps/esri-basemap-gallery/esri-basemap-gallery/esri-basemap-gallery.component.ts, src/angular-maps/esri-config/esri-loader.service.ts, src/angular-maps/esri-layer-list/esri-layer-list/esri-layer-list.component.ts, src/angular-maps/esri-legend/esri-legend/esri-legend.component.ts, src/angular-maps/esri-web-map/esri-web-map/esri-web-map.component.ts, src/angular-maps/esri-web-scene/esri-web-scene/esri-web-scene.component.ts
This is due to Zone.js not working with async/await: https://github.com/angular/angular/issues/31730
=> refactor: replace async/await with plain promises

src/angular-core/styles/includes/_overlay.scss
(autocomplete, dropdown, select)
=> fix: fix style offset of panel divider line in 4k resolution

src/angular-public/search/search/search.component.spec.ts, src/angular-public/search/search/search.component.ts
=> fix(public): close autocomplete panel when starting to search

src/angular-core/schematics/ng-update/migrations/form-field-migration.ts
sbb-form-field now requires a compatible form field control. In the migration we add
a warning, that this is now required and where in the consumers code this is a problem.
=> fix: add warning in migration for form-field control requirement

src/angular-business/processflow/processflow/processflow.component.html, src/angular-business/processflow/processflow/processflow.component.scss, src/angular-public/processflow/processflow/processflow.component.html, src/angular-public/processflow/processflow/processflow.component.scss, src/showcase/app/business/business-examples/processflow-examples/processflow-example/processflow-example.component.html, src/showcase/app/business/business-examples/processflow-examples/processflow-example/processflow-example.component.ts, src/showcase/app/business/business-examples/processflow-examples/processflow-examples.module.ts
=> feat(business): business styles for processflow

src/angular-public/accordion/expansion-panel/expansion-panel.component.scss
=> fix: allow sticky elements in expansion panel content

src/angular-business/tooltip/tooltip/tooltip.component.ts, src/angular-core/base/tooltip/tooltip-base.ts, src/angular-public/tooltip/BUILD.bazel, src/angular-public/tooltip/tooltip/tooltip.component.spec.ts
=> fix: prevent closing tooltip on outside mouseup

src/angular-core/i18n/xlf/messages.de-CH.xlf, src/angular-core/i18n/xlf/messages.fr-CH.xlf, src/angular-core/i18n/xlf/messages.it-CH.xlf, src/angular-core/i18n/xlf/messages.xlf, src/angular-core/i18n/xlf2/messages.de-CH.xlf, src/angular-core/i18n/xlf2/messages.fr-CH.xlf, src/angular-core/i18n/xlf2/messages.it-CH.xlf, src/angular-core/i18n/xlf2/messages.xlf, src/angular-public/autocomplete/autocomplete/autocomplete-trigger.directive.ts, src/angular-public/search/search/search.component.html, src/angular-public/search/search/search.component.ts
=> fix(public): fix autocomplete accessibility and shadow DOM usage of sbb-search

src/angular-core/icon/icon-cdn-provider.ts, src/angular-core/icon/icon-registry-wrapper-provider.ts
=> chore: update icon registry to v1.12.0

src/angular-public/breadcrumb/breadcrumb/breadcrumb.component.ts
=> fix: breadcrumb check fails due lifecycle issue

src/angular-business/notification-toast/notification-toast-container.component.scss, src/angular-business/notification/notification/notification.component.scss, src/angular-public/notification/notification/notification.component.scss
=> fix: align icon in notifications on top

src/angular-business/header/header/header.component.scss
=> fix: reserve space for environment in header

src/angular-core/base/processflow/processflow-base.ts, src/angular-public/processflow/processflow/processflow.component.spec.ts
=> fix: allow sbb-processflow to be initialized asynchronous

src/angular-public/input/input.spec.ts, src/angular-public/input/input.ts, src/angular/form-field/input.spec.ts, src/angular/form-field/input.ts
=> fix: display placeholder attribute when using sbbInput directive

src/angular-public/accordion/expansion-panel/expansion-panel.component.scss
=> fix: hide content of nested accordion in collapsed state

src/angular-public/accordion/expansion-panel-header/expansion-panel-header.component.scss, tools/package-info/bazel-bin.ts
=> fix: keep accordion panel height if expand icon is hidden

src/angular-public/autocomplete/autocomplete.md, src/angular/autocomplete/autocomplete.md
=> docs: add known issues section to autocomplete

src/components-examples/angular-maps/esri-basemap-gallery/esri-basemap-gallery/esri-basemap-gallery-example.html, src/components-examples/angular-maps/esri-basemap-gallery/esri-basemap-gallery/esri-basemap-gallery-example.ts, src/components-examples/angular-maps/esri-layer-list/esri-layer-list/esri-layer-list-example.html, src/components-examples/angular-maps/esri-layer-list/esri-layer-list/esri-layer-list-example.ts, src/components-examples/angular-maps/esri-legend/esri-legend/esri-legend-example.html, src/components-examples/angular-maps/esri-legend/esri-legend/esri-legend-example.ts, src/components-examples/angular-maps/esri-web-map/esri-web-map/esri-web-map-example.html, src/components-examples/angular-maps/esri-web-map/esri-web-map/esri-web-map-example.ts, src/components-examples/angular-maps/esri-web-scene/esri-web-scene/esri-web-scene-example.html, src/components-examples/angular-maps/esri-web-scene/esri-web-scene/esri-web-scene-example.ts, src/showcase-merge/app/shared/meta.ts, src/showcase/app/maps/maps-examples/esri-basemap-gallery-examples/esri-basemap-gallery-example/esri-basemap-gallery-example.component.ts, src/showcase/app/maps/maps-examples/esri-layer-list-examples/esri-layer-list-example/esri-layer-list-example.component.ts, src/showcase/app/maps/maps-examples/esri-web-map-examples/esri-web-map-example/esri-web-map-example.component.ts, src/showcase/app/maps/maps-examples/esri-web-scene-examples/esri-web-scene-example/esri-web-scene-example.component.ts
Adapt maps changes of the showcase (https://github.com/sbb-design-systems/sbb-angular/commit/6fc5268fde95d483ecb6a23d8e34300372b0fd3f) to the showcase-merge to be in sync
=> refactor(angular): match merge maps examples with old examples

src/angular-public/textarea/textarea/textarea.component.spec.ts, src/angular-public/textarea/textarea/textarea.component.ts, src/angular/textarea/textarea/textarea.spec.ts, src/angular/textarea/textarea/textarea.ts
=> fix: resize textarea correctly on content pasting

src/angular-public/select/select/select.component.scss, src/angular/select/select/select.scss
=> fix(business): fix placeholder color of select

src/angular-core/styles/includes/_form.scss
=> fix: use correct sizing for input fields

src/angular-public/textarea/BUILD.bazel, src/angular-public/textarea/textarea.md, src/angular-public/textarea/textarea/textarea.component.html, src/angular-public/textarea/textarea/textarea.component.scss, src/angular-public/textarea/textarea/textarea.component.spec.ts, src/angular-public/textarea/textarea/textarea.component.ts, src/angular-public/typography.scss, src/angular/styles/_typography.scss, src/angular/textarea/textarea.md, src/angular/textarea/textarea/textarea.html, src/angular/textarea/textarea/textarea.scss, src/angular/textarea/textarea/textarea.spec.ts, src/angular/textarea/textarea/textarea.ts, src/showcase/styles.scss
=> fix: don't reset height for sbb-textarea

src/angular/datepicker/calendar/calendar-header.html, src/angular/datepicker/calendar/calendar-header.spec.ts, src/angular/datepicker/calendar/calendar.spec.ts, src/angular/datepicker/datepicker-content/datepicker-content.scss, src/angular/datepicker/datepicker/datepicker.scss, src/angular/styles/_typography.scss, src/angular/styles/includes/_mixins.scss, src/components-examples/angular/datepicker/datepicker-lean-date-adapter/datepicker-lean-date-adapter-example.html, src/components-examples/angular/datepicker/datepicker-standalone-forms/datepicker-standalone-forms-example.html
@jeripeierSBB I would like to discuss the size of the "spickel" in relation to the tooltip one.
=> refactor: optimize datepicker styles

src/angular/breadcrumb/breadcrumbs.scss, src/angular/styles/_typography.scss
=> refactor: optimize breadcrumb styles

src/angular/datepicker/date-input/date-input.directive.ts, src/angular/datepicker/datepicker/datepicker.spec.ts, src/angular/datepicker/datepicker/datepicker.ts, src/components-examples/angular/datepicker/datepicker-date-range/datepicker-date-range-example.html
=> fix(angular/datepicker): reset model of connected datepicker if datepicker value changes

src/angular/header-lean/header-lean.md, src/angular/header-lean/header.scss
=> feat(angular/header): add environment `local` with color `autumn`

src/angular/schematics/ng-add/migrations/style-import-migration.spec.ts, src/angular/schematics/ng-add/migrations/style-import-migration.ts
https://github.com/angular/components/pull/24169
=> fix(angular/schematics): remove file extensions in tilde migration

src/angular/datepicker/BUILD.bazel, src/angular/datepicker/date-input/date-input.directive.ts, src/angular/datepicker/datepicker/datepicker.html, src/angular/datepicker/datepicker/datepicker.spec.ts, src/angular/datepicker/datepicker/datepicker.ts, src/angular/input/input.spec.ts, src/angular/input/input.ts, src/angular/notification/notification.ts, src/angular/processflow/processflow.spec.ts, src/angular/select/select/select.html, src/angular/select/select/select.scss, src/angular/select/select/select.spec.ts, src/angular/select/select/select.ts, src/angular/styles/_typography.scss, src/angular/textarea/textarea/textarea.html, src/angular/textarea/textarea/textarea.spec.ts, src/angular/textarea/textarea/textarea.ts, src/components-examples/angular/datepicker/datepicker-simple-reactive/datepicker-simple-reactive-example.html, src/components-examples/angular/datepicker/datepicker-simple-reactive/datepicker-simple-reactive-example.ts, src/components-examples/angular/form-field/form-field-text-input-attribute-label/form-field-text-input-attribute-label-example.html, src/components-examples/angular/form-field/form-field-text-input-attribute-label/form-field-text-input-attribute-label-example.ts, src/components-examples/angular/input/input-overview/input-overview-example.html, src/components-examples/angular/select/BUILD.bazel, src/components-examples/angular/select/index.ts, src/components-examples/angular/select/select-native/select-native-example.html, src/components-examples/angular/select/select-native/select-native-example.ts, src/components-examples/angular/select/select-reactive-forms/select-reactive-forms-example.html, src/components-examples/angular/select/select-reactive-forms/select-reactive-forms-example.ts, src/components-examples/angular/time-input/time-input-reactive-forms/time-input-reactive-forms-example.html, src/components-examples/angular/time-input/time-input-reactive-forms/time-input-reactive-forms-example.ts
Closes #916 
Closes #917 
Closes #918
=> fix(angular): fix styles and behavior of form inputs in readonly mode

src/angular/menu/menu.spec.ts, src/angular/menu/menu.ts
https://github.com/angular/components/pull/23310
=> fix(angular/menu): not interrupting keyboard events to other overlays

src/angular/button/button.html, src/angular/styles/_typography.scss, src/components-examples/angular/button/BUILD.bazel, src/components-examples/angular/button/button-with-icon/button-with-icon-example.css, src/components-examples/angular/button/button-with-icon/button-with-icon-example.html, src/components-examples/angular/button/button-with-icon/button-with-icon-example.ts, src/components-examples/angular/button/index.ts, src/components-examples/angular/button/link-group/link-group-example.ts, src/components-examples/angular/button/link/link-example.ts
=> fix(angular/button): align sbb-icon inside buttons

.github/workflows/angular-components-sync-workflow.yml, package.json, scripts/angular-components-sync-test.ts, scripts/angular-components-sync.ts, yarn.lock
=> chore(angular): sync angular components commits in github issue

src/angular/migration-guide.md, src/angular/schematics/ng-add/data/output-names.ts, src/angular/schematics/ng-add/test-cases/merge/tooltip_expected_output.ts, src/angular/schematics/ng-add/test-cases/merge/tooltip_input.ts, src/angular/tooltip/tooltip.spec.ts, src/angular/tooltip/tooltip.ts
=> feat(angular/tooltip): add dismissed output

tools/schematics/bazel/index.js, tools/schematics/bazel/sass-dependency-resolver.ts
Fixes a problem with the detection of `@use` in scss files.
=> build: fix baz schematics

src/angular/tooltip/tooltip-wrapper.spec.ts, src/angular/tooltip/tooltip-wrapper.ts, src/angular/tooltip/tooltip.ts
=> fix(angular/tooltip): add dismissed output to tooltip wrapper

src/angular/search/search.scss
=> fix(angular/search): ensure icon position is correctly aligned

src/angular/tabs/_tabs.scss
Improves 125% screen size behavior
=> fix(angular/tabs): fix padding in lean design

src/angular/styles/_typography.scss
=> fix(angular/styles): fix selection-item styles

src/angular/datepicker/datepicker/datepicker.scss, src/angular/datepicker/datepicker/datepicker.spec.ts
This bug only appears when the datepicker is not inside an `sbb-form-field`. Therefore I've added an test to ensure it is full width.
=> fix(angular/datepicker): make input full width

src/angular/styles/_typography.scss
=> fix(angular/lightbox): hide scrollbar from scroll lock container

src/angular/dialog/dialog-content-directives.ts, src/angular/i18n/xlf/messages.xlf, src/angular/i18n/xlf2/messages.xlf, src/angular/lightbox/lightbox-content-directives.ts
=> fix(angular/lightbox): fix aria-label on close button

src/angular/i18n/xlf/messages.fr-CH.xlf, src/angular/i18n/xlf2/messages.fr-CH.xlf
=> fix(angular/sidebar): fix translations of collapse and expand

src/angular/schematics/ng-add/migrations/secondary-entry-points-migration.ts
Replaces all of our usages of deprecated `ts.create*` APIs with their non-deprecated counterparts.
=> refactor(angular/schematics): replace usages of deprecated TypeScript APIs

src/angular/styles/_typography.scss
=> fix(angular/table): don't override definitions of non `.sbb-table` tables

src/angular/menu/menu.scss, src/components-examples/angular/menu/index.ts, src/components-examples/angular/menu/menu-grouping/menu-grouping-example.html, src/components-examples/angular/menu/menu-grouping/menu-grouping-example.ts
=> feat(angular/menu): allow grouping of elements

src/angular/styles/_typography.scss
=> fix(angular/styles): clear float in fieldset legend

src/angular/styles/_typography.scss
This PR fixes empty radio buttons in Microsoft's high contrast mode.
Closes #1326
=> fix(angular/radio): fix empty radio in high-contrast-mode

src/angular/styles/_typography.scss, src/angular/tooltip/tooltip.md
=> feat(angular/tooltip): provide style class to use tooltip inline

RELEASE.md, RELEASE_HOW_TO.md
=> docs: how to release

src/angular/dialog/dialog-container.ts
Align to changes from angular components
=> refactor(angular/dialog): implement delayFocusTrap option

src/angular/styles/_typography.scss, src/angular/tooltip/tooltip-wrapper.html, src/angular/tooltip/tooltip-wrapper.spec.ts, src/angular/tooltip/tooltip-wrapper.ts, src/angular/tooltip/tooltip.md, src/angular/tooltip/tooltip.scss, src/angular/tooltip/tooltip.spec.ts, src/angular/tooltip/tooltip.ts
=> feat(angular/tooltip): allow zero padding styling

src/angular/styles/_typography.scss, src/angular/table/table.md, src/angular/table/table.spec.ts, src/angular/table/table/table-wrapper.ts
https://github.com/angular/components/commit/8dfbbed549621546d72dda341aa268cbb44fed97
=> fix(angular/table): accessibility improvements on table

src/angular/icon/icon.scss
=> fix(angular/icon): fix inline icon styles

package.json, src/angular/table/table/table-data-source.ts, tools/dgeni/index.bzl, tools/highlight-files/index.bzl, tools/markdown-to-html/index.bzl, tools/package-docs-content-legacy/index.bzl, tools/package-docs-content/index.bzl, yarn.lock
Bumps up our version of TypeScript to 4.7 and resolves a couple of build errors.
=> build: update to TypeScript 4.7

src/angular/dialog/dialog-config.ts, src/angular/dialog/dialog-container.ts, src/angular/dialog/dialog-ref.ts, src/angular/dialog/dialog.module.ts, src/angular/dialog/dialog.ts, src/angular/lightbox/lightbox-container.ts, src/angular/lightbox/lightbox-ref.ts, src/angular/lightbox/lightbox.module.ts, src/angular/lightbox/lightbox.spec.ts, src/angular/lightbox/lightbox.ts
Switches the angular dialog to be based on the CDK dialog.
=> feat(angular/dialog): switch to CDK dialog

src/angular/styles/_typography.scss
Fix vertical spacing in checkbox-panel and radio-button-panel on small devices and improve overall responsiveness
=> fix(angular/checkbox-panel): correct spacing in checkbox-panel

src/angular/checkbox/checkbox.spec.ts
PR to keep in sync with angular/components
=> chore: update checkbox test

src/angular/schematics/ng-add/index.spec.ts, src/angular/schematics/ng-add/setup-project.ts
PR to keep in sync with angular/components
=> chore: update project setup script

src/angular/schematics/migration.json, src/angular/schematics/ng-update/index.ts
Prepares the schematics infrastructure for the next major version.
=> build: set up schematics for version 15

src/showcase/assets/stack-blitz/tsconfig.json
This fixes multiple StackBlitz examples, e.g. ProcessFlow and FormField.
=> docs: update stackblitz tsconfig.json

src/angular/notification/notification.scss, src/angular/notification/notification.spec.ts, src/angular/notification/notification.ts, src/components-examples/angular/notification/simple-notification/simple-notification-example.html
=> feat(angular/notification): add type `info-light`

src/angular/tooltip/tooltip.spec.ts, src/angular/tooltip/tooltip.ts
=> fix(tooltip): allow click event bubbling on hover trigger

src/angular/i18n/xlf/messages.xlf, src/angular/i18n/xlf2/messages.xlf, src/angular/search/header-search.ts, src/angular/search/search.spec.ts
=> fix(angular/search): close and open header search programmatically

src/angular/styles/_typography.scss
=> fix(multiple): do not override styles of SBB.ch

src/angular/processflow/step-header.scss
=> fix(angular/processflow): avoid letters being cut off

src/angular/processflow/processflow.html, src/angular/processflow/processflow.scss, src/angular/processflow/processflow.spec.ts
This bug was caused by c6aad0bf1dbef9406bfa83e38029da0cb324a3b7
Closes #1650
=> fix(angular/processflow): fix bug that inactive steps are displayed

src/angular/loading-indicator/loading-indicator.scss
=> fix(sbb-loading): fix 3d transformation in firefox

src/angular/lightbox/lightbox.module.ts, src/angular/lightbox/public-api.ts
=> fix(angular/lightbox): correct dependency tree for CDK dialog

src/angular/button/button.ts
=> fix(angular/button): support content change between text and no text

src/journey-maps/package.json
=> fix(journey-maps/web-component): export the web-component 

renovate.json
Add `zone.js` to `ignoreDeps` and update it together with `@angular/core`.
=> ci: make renovate ignore zone.js

src/angular/processflow/step-header.scss, src/angular/tabs/_tabs.scss
Adds high-contrast-mode for disabled tabs and processflow steps.
=> fix(multiple): add HCM for disabled tabs and steps

src/journey-maps/angular/journey-maps.interfaces.ts, src/journey-maps/web-component/showcase.ts
=> feat(journey-maps): add new POIs subcategories

renovate.json
update together with `@angular/build-tooling`
=> chore(deps): ignore `@types/yargs` in renovate.json

src/journey-maps/package.json
=> fix(journey-maps): export web component CSS in package.json

src/angular/menu/menu-trigger.ts, src/angular/menu/menu.spec.ts
Update to be in sync with `angular/components`. See https://github.com/angular/components/commit/77f0a77831a009aceb65b7e831e0c08ec7afdae7
=> test(angular/menu): ensure aria-expanded is updating in an OnPush component

package.json, src/angular-experimental/schematics/BUILD.bazel, src/angular/schematics/BUILD.bazel, src/angular/schematics/utils.ts, yarn.lock
Remove deprecated @types/parse5 library and update to latest parse5 version exported by the CDK
=> build: update to latest version of parse5

src/angular/loading-indicator/loading-indicator.md
=> docs(loading-indicator): add note about fullbox mode

package.json, renovate.json, yarn.lock
This is to avoid renovate noise. I've created a card in our project instead.
=> chore(deps): bump @angular/bazel to 15.0.4

src/components-examples/journey-maps/angular/journey-maps-full/journey-maps-full-example.ts, src/journey-maps/angular/services/map/map-routes.service.ts
=> feat(journey-maps): improved route hover

src/components-examples/journey-maps/angular/journey-maps-full/journey-maps-full-example.html
=> feat(journey-maps): add dropdown for POI category selection

src/journey-maps/angular/BUILD.bazel, src/journey-maps/angular/components/leit-poi/leit-poi.scss, src/journey-maps/angular/components/level-switch/level-switch.scss, src/journey-maps/angular/components/teaser/teaser.scss, src/journey-maps/angular/journey-maps.scss, src/journey-maps/angular/style/_functions.scss, src/journey-maps/web-component/styles.scss
=> fix(journey-maps): keep button icon visible against black background

src/angular/lightbox/lightbox-container.ts, src/components-examples/journey-maps/angular/journey-maps-full/journey-maps-full-example.ts
=> fix: make rxjs imports forward compatible

src/journey-maps/angular/BUILD.bazel, src/journey-maps/angular/components/attribution/attribution.html, src/journey-maps/angular/components/attribution/attribution.scss, src/journey-maps/angular/components/attribution/attribution.ts
=> fix(journey-maps): fix multiline attribution style

src/journey-maps/web-component/web-component.md
=> docs(journey-maps): document how to configure listenerOptions

src/angular/icon/icon-registry.ts, src/angular/icon/icon.spec.ts, src/angular/icon/icon.ts, src/showcase/app/angular/icon-overview/cdn-icon-list/cdn-icon-dialog/cdn-icon-dialog.component.ts, src/showcase/app/angular/icon-overview/cdn-icon-list/cdn-icon-list.component.html, src/showcase/app/angular/icon-overview/cdn-icon-list/cdn-icon-list.component.ts, src/showcase/app/angular/icon-overview/cdn-icon-list/cdn-icon/cdn-icon.component.html, src/showcase/app/angular/icon-overview/cdn-icon-list/cdn-icon/cdn-icon.component.scss, src/showcase/app/angular/icon-overview/cdn-icon-list/cdn-icon/cdn-icon.component.ts, src/showcase/app/angular/icon-overview/cdn-icon.service.ts, src/showcase/app/angular/icon-overview/icon-overview.component.ts
=> feat(angular/icon): update to new icons and pictograms

package.json
That's primary a fix for local development. The last major release was created on the release branch.
=> chore: update library version in main branch

src/angular/core/common-behaviors/variant.ts, src/showcase/app/app.component.html, src/showcase/app/variant-switch.ts
I created a new branch called `feature/dark-mode` and will create separate pull requests in this branch. Later, we'll merge everything together.
=> feat(multiple): add dark mode variant

src/angular/styles/_typography.scss
@n1thushan, thanks for the nice work for the dark mode button!
My PR looks like there were a lot of changes necessary but that's not the case. I just did some search & replace to match the naming conventions (you could not know this) and removed some `where(html.sbb-lean)` conditions.
=> feat(angular/button): updates for dark mode

src/components-examples/journey-maps/angular/journey-maps-full/journey-maps-full-example.html, src/components-examples/journey-maps/angular/journey-maps-full/journey-maps-full-example.ts
=> fix(journey-maps): hide geolocate button by default

package.json, src/angular/styles/_typography.scss, src/showcase/app/angular/icon-overview/cdn-icon-list/cdn-icon/cdn-icon.component.scss, src/showcase/styles.scss, yarn.lock
highlight.js library still needs to be implementet
=> feat(angular/showcase): implement dark mode

src/angular/toggle/toggle.md
=> docs(angular/toggle): clarify that first option is selected by default

src/angular/datepicker/calendar/calendar.scss, src/angular/datepicker/datepicker-content/datepicker-content.scss, src/angular/dialog/dialog.scss, src/angular/file-selector/file-selector.scss, src/angular/header-lean/header-menu-trigger.scss, src/angular/header-lean/header.scss, src/angular/lightbox/lightbox.scss, src/angular/menu/menu.scss, src/angular/sidebar/icon-sidebar/icon-sidebar.scss, src/angular/sidebar/sidebar/sidebar.scss, src/angular/styles/_typography.scss, src/angular/tooltip/tooltip.scss, src/showcase/app/variant-switch.ts
This changes the default dark mode background color to midnight. Additionally, some dark mode styles are fixed according to feedback from UX.
=> fix(multiple): change dark mode background to midnight and fix some styles

src/components-examples/journey-maps/angular/journey-maps-full/journey-maps-full-example.ts, src/journey-maps/angular/components/level-switch/services/level-switcher.ts, src/journey-maps/angular/components/level-switch/services/map-layer-filter.ts
=> fix(journey-maps): prevent console errors

src/journey-maps/angular/journey-maps.ts
=> fix(journey-maps): refresh pois after style change

src/journey-maps/angular/components/level-switch/level-switch-horizontal.html, src/journey-maps/angular/components/level-switch/level-switch-horizontal.scss, src/journey-maps/angular/components/level-switch/level-switch-horizontal.ts
=> fix(journey-maps): acceptance test fixes

src/journey-maps/angular/components/level-switch/level-switch-horizontal.html, src/journey-maps/angular/components/level-switch/level-switch-horizontal.ts
=> fix(journey-maps): prevent opening side buttons on timeout

src/journey-maps/angular/components/level-switch/level-switch-horizontal.ts
Fixes the animation of the horizontal level switcher 
Refs: ROKAS-1884
=> fix(journey-maps): fix horizontal level switch animation

src/angular/header-lean/header.scss
=> fix(angular/header-environment): fix text color in dark mode

src/angular/i18n/xlf/messages.xlf, src/angular/i18n/xlf2/messages.xlf, src/angular/tag/BUILD.bazel, src/angular/tag/tag-link.html, src/angular/tag/tag-link.ts, src/angular/tag/tag.html, src/angular/tag/tag.md, src/angular/tag/tag.scss, src/angular/tag/tag.ts, src/angular/tag/tags.spec.ts, src/components-examples/angular/tag/index.ts, src/components-examples/angular/tag/tag-with-icon/tag-with-icon-example.html, src/components-examples/angular/tag/tag-with-icon/tag-with-icon-example.ts
This PR enables the placement of icons inside tags.
Closes #2072
=> feat(angular/tag): display icons inside tags

.github/workflows/maintenance-changelog.yml, .github/workflows/maintenance-cherry-pick.yml, scripts/update-maintenance-issue.mts
Convert the maintenance workflow to ECMAScript
=> ci: fix maintenance workflow

src/angular/lightbox/lightbox.ts
This provides the lightbox service in root and adds deprecations to unused injection tokens.
=> fix(angular/lightbox): provide lightbox service in root

src/angular/tabs/paginated-tab-header.ts, tslint.json
Also update the lint configuration to the current state.
=> refactor(angular/tabs): remove use of zone.onStable for aligning tabs

src/angular/tooltip/tooltip.spec.ts, src/angular/tooltip/tooltip.ts
Fixes that we were setting an `aria-describedby` even if the tooltip won't show up because it's disabled.
=> fix(angular/tooltip): remove aria-describedby when disabled

src/journey-maps/angular/components/level-switch/level-switch-horizontal.ts, src/journey-maps/angular/journey-maps.ts
=> fix(journey-maps): manual change detection for web component

src/components-examples/journey-maps/angular/journey-maps-style-options/journey-maps-style-options-example.ts, src/components-examples/journey-maps/angular/shared/extrusion/bern.ts, src/journey-maps/angular/journey-maps.interfaces.ts, src/journey-maps/angular/journey-maps.ts
=> docs(journey-maps): include extra files

src/journey-maps/angular/journey-maps.ts
replacement PR for https://github.com/sbb-design-systems/sbb-angular/pull/2182
=> docs(journey-maps): add documentation for 'isLevelSwitchHorizontal'

src/journey-maps/angular/journey-maps.ts
=> fix(journey-maps): always broadcast rotation and pitch

src/angular/tooltip/tooltip.ts
This is done to align layout updates with other components using afterNextRender.
=> perf(angular/tooltip): use afterNextRender to invoke aria describer

src/angular/dialog/dialog-config.ts, src/angular/lightbox/lightbox-config.ts
* `SbbDialogConfig.componentFactoryResolver` has been removed
* `SbbLightboxConfig.componentFactoryResolver` has been removed
=> fix(multiple): remove remaining references to ComponentFactoryResolver

src/angular/accordion/accordion.spec.ts, src/angular/notification-toast/notification-toast.spec.ts
Removes the remaining opt-out of exhaustive checks
=> test(multiple): enable exhaustive checks

src/journey-maps-wc/getting-started.md
This updates the journey maps documentation to fit the new module structure.
=> docs: update documentation for journey maps web component
