sbb-design-systems/sbb-angular

- projects/sbb-esta/angular-business/src/lib/time-input/time-input.ts
- projects/sbb-esta/angular-business/src/public-api.ts
- projects/sbb-esta/angular-public/src/styles/typography/_form.scss
Exposes the time input component for business applications.
This also changes the height and width of time input components. **This PR should be merged after #32 for correct styling.**
> feat(business/time-input): expose time input component for business

- projects/sbb-esta/angular-public/src/lib/radio-button/_radio-button.scss
Changes the grey color used in the public theme #666 (sbbColorGrey) to the one needed for the business theme #686868 (sbbColorGranite) for the radio-button component.
> fix(business/radio-button): change grey color of radio-buttons

- projects/sbb-esta/angular-business/src/lib/button/button/button.component.scss
- projects/sbb-esta/angular-public/src/lib/button/styles/_button-variables.scss
This PR adds an opacity to the fonts on disabled buttons for all button types and changes the text color and text color on hover for the ghost button type.
> fix(business/button): change font opacity for disabled buttons

- projects/sbb-esta/angular-public/src/styles/common/_form.scss
change the gray color to fit style guide for input field labels and borders from #666 (sbbColorGrey) to #686868 (sbbColorGranite).
> fix(business/field): change gray color to fit style guide

- projects/sbb-esta/angular-public/src/lib/option/styles/_option-variables.scss
This changes the color of the active option to red, as opposed to as discussed in #41. They adapted the style guide to this, because when using keyboard navigation to select an item the item should be red instead of black.
This affects the select and autocomplete component.
> fix(business/option): change color of active/hover to red125

- projects/sbb-esta/angular-public/src/lib/autocomplete/styles/_autocomplete-variables.scss
- projects/sbb-esta/angular-public/src/lib/option/styles/_option-base.scss
- projects/sbb-esta/angular-public/src/lib/select/select/select.component.spec.ts
- projects/sbb-esta/angular-public/src/lib/select/styles/_select-base.scss
- projects/sbb-esta/angular-public/src/lib/select/styles/_select-variables.scss
- projects/sbb-esta/angular-public/src/styles/common/_form.scss
- projects/sbb-esta/angular-public/src/styles/typography/_form.scss
This PR changes the placement of the arrow trigger in the select component from relative to absolute. This is similar to the arrows for the datepicker component. The reason for this change is, that otherwise the icon is higher than a normal field in the business library and therefore form elements are of different height when placed next to each other.
This change affects the public and business library.
> fix(select): change arrow trigger position to absolute

- projects/sbb-esta/angular-business/src/lib/accordion/accordion.ts
- projects/sbb-esta/angular-business/src/public-api.ts
- projects/sbb-esta/angular-public/src/lib/accordion/accordion/accordion.component.spec.ts
- projects/sbb-esta/angular-public/src/lib/accordion/expansion-panel-header/expansion-panel-header.component.html
- projects/sbb-esta/angular-public/src/lib/accordion/expansion-panel-header/expansion-panel-header.component.scss
- projects/sbb-esta/angular-public/src/lib/accordion/expansion-panel/expansion-panel.component.spec.ts
- projects/sbb-esta/angular-public/src/lib/accordion/styles/_accordion-header.scss
- projects/sbb-esta/angular-public/src/lib/accordion/styles/_accordion-panel.scss
- projects/sbb-esta/angular-public/src/lib/accordion/styles/_accordion-variables.scss
Exposes the accordion component for business applications. Styling should be accoring to the [SBB Style Guide for Business Applications](https://digital.sbb.ch/en/webapps/components/accordion).
For the toggle I used a background-svg similar to the native select, for not needing to tamper with the html code of the components. Otherwise I would have to extend multiple components just to exchange the icon.
Closes #77
> feat(business/accordion): expose accordion for business

- projects/sbb-esta/angular-business/src/lib/checkbox/checkbox/checkbox.component.spec.ts
- projects/sbb-esta/angular-public/src/lib/checkbox/checkbox/checkbox-base.ts
- projects/sbb-esta/angular-public/src/lib/checkbox/checkbox/checkbox.component.ts
Moves the binding of the class sbb-checkbox to the base checkbox component. Otherwise the correct styling is not applied to business components.
If possible, can you please create a patch-release of the business package after merging.
> fix(business/checkbox): add sbb-checkbox class to public and business

- projects/sbb-esta/angular-public/src/lib/toggle/toggle-option/toggle-option.component.ts
IE11 doesn't support .forEach on NodeLists, which was causing the issue.
An alternative could be adding a generic polyfill for the issue.
> fix(toggle): use for-loop in place of forEach on NodeList (#125)

- projects/sbb-esta/angular-public/src/lib/accordion/styles/_accordion-panel.scss
This fixes an unwanted jump in padding when the screen gets small for the business theme.
> fix(business/accordion): remove media query breakpoints

- projects/sbb-esta/angular-business/button/src/button/button.component.html
- projects/sbb-esta/angular-business/button/src/button/button.component.ts
I added to necessary instructions directly to the business button. This hopefully displays the icons again. If I have time, I will someday refactor the stylings, so there is another template, but for the moment, I would just like to get it to work. So a bugfix release asap would be appreciated, otherwise I would have to rollback to an older version.
In my tests the directive 
```html
<button sbbButton mode="icon">
<sbb-icon-arrow-right *sbbIcon></sbb-icon-arrow-right>
</button>
```
still did not work, but I hope this is due to my test setup. However,
```html
<ng-template #icon>
<sbb-icon-arrow-right></sbb-icon-arrow-right>
</ng-template>
<button sbbButton mode="icon" [icon]="icon">
```
works fine.
> fix(business/button): add icon content child to component and template

- projects/sbb-esta/angular-public/notification/src/notification/notification.component.spec.ts
- projects/sbb-esta/angular-public/notification/src/notification/notification.component.ts
Allow to perform specific actions on jump mark click.
closes #131
> feat(notification): add optional callbacks to jump marks

- projects/sbb-esta/angular-public/checkbox/src/_checkbox.scss
- projects/sbb-esta/angular-public/radio-button/src/_radio-button.scss
This fixes bugs when used with perfect scrollbar, where Chrome auto scrolls to the native element that sometimes is placed in overflow area.
closes #243
> fix: assure hidden native input elements are positioned close to label

- projects/sbb-esta/angular-public/table/src/table/table-scroll-area.directive.ts
IE11 does not have the variable CSS or the CSS.supports function. In some cases the CSS global variable might have been added, but the CSS.supports function is still missing. In order to avoid a reference error, we check for the type of CSS.supports, if CSS is available.
closes #247
> fix(public): fix the sticky detection for public table

- projects/sbb-esta/angular-core/radio-button/src/radio-button.ts
- projects/sbb-esta/angular-public/radio-button-panel/src/radio-button-panel/radio-button-panel.component.spec.ts
- projects/sbb-esta/angular-public/radio-button/src/radio-button/radio-button.component.spec.ts
BREAKING CHANGE: This change removes support for form control on a radio button. Use sbb-radio-button or sbb-radio-button-panel wrapped in a sbb-radio-group.
> refactor: drop support for form control on radio button

- projects/sbb-esta/angular-business/header/src/header.module.ts
Closes #269
BREAKING CHANGE: The header module no longer exports the DropdownModule. If you use sbb-dropdown with the header, you either should switch to using sbb-header-menu where applicable or you need to add DropdownModule to the NgModule imports.
> fix(business): remove dropdown module from header module

- projects/sbb-esta/angular-keycloak/README.md
- projects/sbb-esta/angular-keycloak/src/lib/auth/auth.module.ts
Closes #97
BREAKING CHANGE: The default identity provider is changed from ADFS to Azure AD.
> refactor(keycloak): change idp hint from adfs to azure ad

- projects/sbb-esta/angular-business/getting-started.md
- projects/sbb-esta/angular-business/ng-package.json
- projects/sbb-esta/angular-business/package.json
- projects/sbb-esta/angular-public/getting-started.md
- projects/sbb-esta/angular-public/ng-package.json
- projects/sbb-esta/angular-public/package.json
BREAKING CHANGE: @sbb-esta/angular-core is now a peer dependency of @sbb-esta/angular-public and @sbb-esta/angular-business. This means consumers of this library will need to install @sbb-esta/angular-core manually via `npm install --save @sbb-esta/angular-core`.
> refactor: change @sbb-esta/angular-core to be a peer dependency

- projects/sbb-esta/angular-business/header/src/header/header.component.scss
Setting routerLinkActive="sbb-active" will apply the active color (darker red) to the element.
Closes #253
> feat(business): add .sbb-active as active link highlight

- projects/sbb-esta/angular-business/notification/src/notification/notification.component.ts
- projects/sbb-esta/angular-public/notification/src/notification/notification.component.ts
This changes the jump mark logic to do nothing, if the referenced id is not found in the document.
> fix: make notification component jump marks fault tolerant

- projects/sbb-esta/angular-core/base/src/checkbox-base.ts
- projects/sbb-esta/angular-core/forms/src/form-field-control.ts
- projects/sbb-esta/angular-core/radio-button/src/radio-button.ts
- projects/sbb-esta/angular-public/file-selector/src/file-selector/file-selector.component.ts
- projects/sbb-esta/angular-public/input/src/input/input.directive.ts
- projects/sbb-esta/angular-public/select/src/select/select.component.ts
- projects/sbb-esta/angular-public/textarea/src/textarea/textarea.component.ts
The inputId property on form components will be replaced by an internal getter based on the id property. Where applicable, the form components will forward focus events (e.g. from a label) to the internal input element.
> refactor: deprecate inputId on form components

- src/public/usermenu/usermenu/usermenu.component.scss
> fix: center align login button in usermenu (IE/Firefox)

- src/angular-public/accordion/expansion-panel-header/expansion-panel-header.component.ts
- src/angular-public/accordion/expansion-panel/expansion-panel.component.spec.ts
- src/showcase/app/public/public-examples/accordion-examples/accordion-example/accordion-example.component.html
- src/showcase/app/public/public-examples/accordion-examples/accordion-example/accordion-example.component.ts
Fixes #377
Currently SSO-int is not working, so I have some time for other stuff :smile:.
The `activeElement` solution is inspired by a similar implementation in the `expansion-panel.component.ts`. I thought about using the FocusMonitor but ultimately preferred a synchronous solution. Critical feedback appreciated.
> fix(accordion): toggle expansion-panel-header only if focused

- src/angular-public/autocomplete/autocomplete/autocomplete-trigger.directive.ts
- src/angular-public/field/form-field-token.ts
- src/angular-public/field/has-form-field-control.ts
- src/angular-public/field/label/label.component.ts
TypeScript type imports (import type {...} from '...') break older TypeScript versions. We revert to fix compatibility.
> fix: revert type imports

- src/angular-business/dialog/dialog/dialog-ref.ts
- src/angular-core/base/tooltip/tooltip-base.ts
- src/angular-public/accordion/expansion-panel/expansion-panel.component.ts
- src/angular-public/breadcrumb/breadcrumbs/breadcrumbs.component.ts
- src/angular-public/datepicker/calendar-body/calendar-body.component.ts
- src/angular-public/datepicker/datepicker/datepicker.component.ts
- src/angular-public/dropdown/dropdown-trigger.directive.ts
- src/angular-public/ghettobox/ghettobox/ghettobox-ref.ts
- src/angular-public/lightbox/lightbox/lightbox-ref.ts
- src/angular-public/search/search/search.component.ts
- src/angular-public/select/select/select.component.ts
- src/angular-public/tag/tag/tag.component.ts
- src/angular-public/textarea/textarea/textarea.component.ts
- src/angular-public/toggle/toggle/toggle.component.ts
- src/showcase/app/public/public-examples/ghettobox-examples/ghettobox-example/ghettobox-example.component.ts
- src/showcase/app/shared/component-viewer-base.ts
Use take(1) instead of first(), since the implementation of tak(1) is far smaller.
> refactor: replace first() operator with simpler take(1)

- src/angular-public/tabs/BUILD.bazel
- src/angular-public/tabs/public-api.ts
- src/angular-public/tabs/tab/tab-content.ts
- src/angular-public/tabs/tab/tab.component.html
- src/angular-public/tabs/tab/tab.component.ts
- src/angular-public/tabs/tabs.md
- src/angular-public/tabs/tabs.module.ts
- src/angular-public/tabs/tabs/tabs.component.spec.ts
Closes #456
Please have a look at the implementation code. If it is okay by you, I will add the necessary documentation for public and business before the merge. I used an implementation similar to the expansion panel and the tabs by Material.
> feat(tabs): allow tabs to be lazy rendered by sbbTabContent directive

- .github/workflows/release-workflow.yml
This only removes the local tag, not the tag in the registry.
> build: do not try to remove latest image

- src/angular-business/table/table-cell/table-cell.component.ts
- src/angular-business/table/table-row/table-row.component.ts
- src/angular-business/table/table/table.component.scss
- src/angular-core/styles/typography/_table.scss
- src/showcase/styles.scss
I extracted the table styling from the business component and merged it with the existing table styles provided in core/typography. The old sbb-* classes now seemed unnecessary as styles are now controlled through standard html directives, so I removed them.
To test, the table provided in the typography documentation should now get styled correctly depending on the selected package (public/business).
> feat(business): extract table business styling

- src/angular-business/table/table/table-data-source.spec.ts
- src/angular-business/table/table/table-data-source.ts
- src/showcase/app/business/business-examples/table-examples/BUILD.bazel
- src/showcase/app/business/business-examples/table-examples/filter-sort-paginator-table-example/filter-sort-paginator-table-example.component.html
- src/showcase/app/business/business-examples/table-examples/filter-sort-paginator-table-example/filter-sort-paginator-table-example.component.scss
- src/showcase/app/business/business-examples/table-examples/filter-sort-paginator-table-example/filter-sort-paginator-table-example.component.ts
This PR will change the behaviour of SbbDataTableSource. Previously when a property was filtered, null and undefined was still included. Now we no longer include these data entries.
Closes #445
> fix(business): filter null/undefined in table data source

- src/angular-keycloak/README.md
- src/angular-keycloak/src/auth.init.ts
- src/angular-keycloak/src/auth.interceptor.ts
- src/angular-keycloak/src/auth.module.ts
- src/angular-keycloak/src/auth.service.ts
- src/angular-keycloak/src/auth.tokens.ts
- src/angular-keycloak/src/keycloak-config.ts
- src/showcase/app/app.component.html
- src/showcase/app/introduction/introduction.component.html
This deprecates the @sbb-esta/angular-keycloak package. We stronlgy recommend using angular-oauth2-oidc instead.
> chore: deprecate @sbb-esta/angular-keycloak

- src/angular-maps/esri-config/esri-standard-values.const.ts
- src/angular-maps/getting-started.md
Add missing explanation of trustedServers and originsWithCredentialsRequired configuration options, cleaned up default CORS servers.
> docs(maps): add detailed CORS support explanation

- src/angular-public/ghettobox/ghettobox-container/ghettobox-container.component.spec.ts
- src/angular-public/ghettobox/ghettobox/ghettobox.component.spec.ts
- src/angular-public/links/social-link/social-link.component.spec.ts
- test/angular-test-init-spec.ts
Ivy currently only outputs certain errors to the console. This patch fixes this by
catching the errors on the console and throwing them as an error.
> test: mark warnings or errors from console as failure

- src/angular-core/styles/typography/_form.scss
Align height of timeinput with other inputs on large screens.
Before the height was too large.
closes #587
> fix(timeinput): fix height for 4k and 5k screens/breakpoints

- package.json
- src/angular-business/table/table/table.component.ts
- yarn.lock
The Angular CDK introduced a breaking change in version 10.1.2 and again in 10.2.0, which was fixed in 10.2.1: https://github.com/angular/components/pull/20425
Since we adapted to the 10.1.2 change, we also need to adapt to the 10.2.0 change.
> fix(business): adapt CDK changes for sbb-table

- src/angular-core/datetime/business-date-adapter.spec.ts
- src/angular-core/datetime/business-date-adapter.ts
This should fix the issue mentioned in #613. From my point of view, there is no reason for the additional logic and it should be handled the same as when using the NativeDateAdapter.
Closes #613
> fix(core/business-date-adapter): use year pivot to determine century of 2-digit year

- src/angular-business/tooltip/tooltip.md
- src/angular-business/tooltip/tooltip/tooltip.component.html
- src/angular-business/tooltip/tooltip/tooltip.component.scss
- src/angular-public/tooltip/tooltip.md
- src/angular-public/tooltip/tooltip/tooltip.component.html
- src/angular-public/tooltip/tooltip/tooltip.component.scss
- src/angular-public/tooltip/tooltip/tooltip.component.spec.ts
BREAKING CHANGE: This commit changes the css display property of the tooltip trigger
from block to inline-block.
If you still like to use the block variant, use the following css definition: 
`.sbb-tooltip-trigger { display: block; }`.
> fix: change tooltip trigger css display from block to inline-block

- .prettierignore
- src/showcase/app/business/BUILD.bazel
- src/showcase/app/business/business-example-viewer/business-example-viewer.component.html
- src/showcase/app/business/business-example-viewer/business-example-viewer.component.scss
- src/showcase/app/business/business.module.ts
- src/showcase/app/shared/component-viewer/BUILD.bazel
- src/showcase/app/shared/component-viewer/component-viewer.module.ts
- src/showcase/app/shared/component-viewer/example-viewer/example-viewer.component.html
- src/showcase/app/shared/component-viewer/example-viewer/example-viewer.component.scss
- src/showcase/app/shared/component-viewer/example-viewer/example-viewer.component.ts
- src/showcase/app/shared/component-viewer/stackblitz-writer/stackblitz-writer.service.ts
- src/showcase/app/shared/loader-builder.ts
- src/showcase/assets/BUILD.bazel
- src/showcase/assets/stackblitz/angular.json
- src/showcase/assets/stackblitz/src/app/app.module.ts
- src/showcase/assets/stackblitz/src/index.html
- src/showcase/assets/stackblitz/src/main.ts
- src/showcase/assets/stackblitz/src/polyfills.ts
- src/showcase/assets/stackblitz/src/styles.css
- src/showcase/assets/stackblitz/tsconfig.json
- tools/stackblitz-module-template/BUILD.bazel
- tools/stackblitz-module-template/bazel-bin.ts
- tools/stackblitz-module-template/tsconfig.json
- tslint.json
@kyubisation this is an initial draft of what the implementation of the Stackblitz example opener could look like. Before trying to tidy up the rough cut I'd like to get your opinion, especially on the following points:
- Most differences between this implementation and the Material Stackblitz opener lie in the StackblitzWriterService in the constructStackBlitzForm() function. I had to add a few lines of logic to be able to display examples with different file names / component names in the new Stackblitz project. I'm not particularly happy with the way this is constructed because it 1) creates linting errors through the "replacement placeholders" in the module files and 2) feels a bit sketchy as a whole. I'd be very much open for other ideas in this area.
- I set the dependency versions …
> feat(stackblitz): allow opening examples in new Stackblitz project

- src/angular-business/links/link.component.scss
- src/angular-business/links/link.component.ts
To follow our css naming guide lines we had to rename the following css class of sbb-link-business.
BREAKING CHANGE: css class `.sbb-link-normal` was renamed to `.sbb-link-business-normal`.
css class `.sbb-link-stretch` was renamed to `.sbb-link-business-stretch`.
> fix(business): fix link stretch mode and adapt css classes

- src/angular-business/header/header/header.component.scss
Correct header title according to https://digital.sbb.ch/de/webapps/modules/header
* left title offset of 54px 
* header ribbon text color white
I just noticed, that the left margin is only incorrect when there is no visible hamburger menu, which happens when there is no 'sbb-app-chooser-section' and there is enough space on the screen:
OK
NOK
so fixing the 'margin-left' wont work.
I'll fix it for now by setting a default 'sbb-app-chooser-section', fixing the color would still be nice tough
> fix: fix ribbon color of sbb-header

- src/angular-business/header/header-breakpoint.ts
- src/angular-business/header/header-environment/header-environment.directive.ts
- src/angular-business/header/header-menu-trigger/header-menu-trigger.component.scss
- src/angular-business/header/header-menu-trigger/header-menu-trigger.component.ts
- src/angular-business/header/header-menu/header-menu.component.scss
- src/angular-business/header/header-menu/header-menu.component.ts
- src/angular-business/header/header.md
- src/angular-business/header/header.module.ts
- src/angular-business/header/header/header.component.html
- src/angular-business/header/header/header.component.scss
- src/angular-business/header/header/header.component.ts
- src/angular-business/header/public-api.ts
- src/showcase-merge/app/app.component.html
- src/showcase/app/app.component.html
Adds a flexible mode (css class .sbb-header-flexible) to the header, which
disables the five column layout. This will become the default in a future release.
Also adds the sbb-header-environment element, which replaces the environment
and environmentColor inputs (which are now deprecated).
See header documentation for details.
> feat(business): add flexible mode and environment element for header

- src/angular-core/styles/includes/_checkbox.scss
- src/angular-public/option/option/option.component.scss
- src/angular/checkbox/checkbox.html
- src/angular/core/option/pseudo-checkbox.html
- src/angular/styles/_typography.scss
Previously the checkbox tick was positioned slightly below specification.
This has been fixed in the icon CDN, which caused the tick to be placed
above the intended position. This change fixes the positioning.
> fix: remove positioning fix for tick

- src/angular-business/contextmenu/contextmenu/contextmenu.component.scss
- src/angular-core/icon/icon.scss
- src/angular/icon/icon.scss
- src/angular/select/select/select.scss
- src/angular/styles/_typography.scss
The current selector is fairly aggressive and requires constructs
like .sbb-icon.sbb-icon {} to overwrite reliably. This change should
address that problem partially.
> refactor: lower specificity of .sbb-icon-fit selector

- src/angular-business/header/header/header.component.ts
Setting a value synchronously in ngAfterViewInit causes a ExpressionChangedAfterItHasBeenCheckedError.
Waiting a tick via Promise.resolve() solves this issue.
> fix(business): avoid Expression has changed for menus collapsed state

- src/angular-public/tabs/tabs/tabs.component.spec.ts
- src/angular-public/tabs/tabs/tabs.component.ts
This prevents problems when tabs are opened programmatically based on external information,
such as query params.
Closes #638
> fix(tabs): prevent re-creation of existing tab instances on (redundant) activation of active tab

- src/angular-maps/getting-started.md
angular-maps component has to be used with the same esri-loader version as used on build time of
the component. any other, more recent version does not work properly. Currently, the matching
and working version is version is 2.13.0.
> docs(maps): specifiy esri-loader version to use

- package.json
- src/angular-core/i18n/xlf/messages.de-CH.xlf
- src/angular-core/i18n/xlf/messages.fr-CH.xlf
- src/angular-core/i18n/xlf/messages.it-CH.xlf
- src/angular-core/i18n/xlf/messages.xlf
- src/angular-core/i18n/xlf2/messages.de-CH.xlf
- src/angular-core/i18n/xlf2/messages.fr-CH.xlf
- src/angular-core/i18n/xlf2/messages.it-CH.xlf
- src/angular-core/i18n/xlf2/messages.xlf
- yarn.lock
The Angular i18n extractor changed the output format for interpolation
elements, which causes consumers to break when using our xlf files.
> fix: update xlf files to fix interpolated entries

- src/angular-core/styles/includes/_form.scss
- src/angular-public/select/select/select.component.scss
- src/angular-public/textarea/textarea/textarea.component.scss
- src/angular/form-field/form-field.md
- src/angular/styles/_typography.scss
- src/angular/textarea/textarea/textarea.scss
- src/components-examples/angular/form-field/form-field-dirty-error-state/form-field-dirty-error-state-example.html
- src/components-examples/angular/form-field/form-field-dirty-error-state/form-field-dirty-error-state-example.ts
- src/components-examples/angular/form-field/form-field-text-input-attribute-label/form-field-text-input-attribute-label-example.html
- src/components-examples/angular/form-field/form-field-text-input-sbb-label/form-field-text-input-sbb-label-example.html
- src/components-examples/angular/form-field/index.ts
Currently when using the `SbbShowOnDirtyErrorStateMatcher`, errors in the form field
will be shown, but the form field itself will not (yet) be shown in an error state.
This PR fixes this by applying the error styles based on the error class from the form field.
> fix: apply error styles based on the error state of the form field

- src/angular-core/styles/typography/_scrollbar.scss
- src/angular/styles/_typography.scss
Sets scrollbar on iOS devices invisible which solves a bug where a scrollbar
is wrongly visible for a short time (until clicking or scrolling) inside the sidebar.
> fix(business): hide sidebar scrollbar on iOS devices

- src/angular-business/chip/chip-input/chip-input.component.html
- src/angular-business/chip/chip-input/chip-input.component.ts
- src/showcase/app/business/business-examples/chip-examples/autocomplete-chip-input-example/autocomplete-chip-input-example.component.html
- src/showcase/app/business/business-examples/chip-examples/autocomplete-chip-input-example/autocomplete-chip-input-example.component.ts
- src/showcase/app/business/business-examples/chip-examples/reactive-forms-chip-input-example/reactive-forms-chip-input-example.component.html
- src/showcase/app/business/business-examples/chip-examples/reactive-forms-chip-input-example/reactive-forms-chip-input-example.component.ts
Currently if enter is pressed in the chips input, the submit event from the surrounding
form is triggered. In order to prevent this from always happening, we check if content
has been entered in the input and if yes, we prevent the form submit. If the inner
input has no value, then the enter press will trigger the form submit.
> fix(business): prevent submit event in chips when pressing enter with content

- src/angular-business/header/header-menu/header-menu.component.ts
Due to SbbHeader being imported as type and directly used as a parameter
type in SbbHeaderMenu, the decorater metadata contained a reference to
SbbHeader, which was not actually available.
Closes #798
> fix(business): avoid metadata inlining for the header

- src/angular-public/form-field/form-field.md
- src/angular-public/form-field/form-field.scss
- src/angular/form-field/form-field.md
- src/angular/form-field/form-field.scss
- src/angular/schematics/ng-add/migrations/merge-refactor-migration.ts
- src/angular/schematics/ng-add/migrations/merge-refactor/form-field-migration.ts
- src/angular/schematics/ng-add/test-cases/merge/form-field_expected_output.ts
- src/angular/schematics/ng-add/test-cases/merge/form-field_input.ts
We are adding the css class `sbb-form-field-flexible-errors`, which can be placed on `sbb-form-field` or any ancestor, which will remove the reserved space for errors and display errors in the normal context flow.
This also deprecates the css class `sbb-form-field-errorless`, which will be removed in a future version.
> feat: add css class for normal error flow inside sbb-form-field

- src/angular-core/styles/typography/_reset.scss
- src/angular/styles/_typography.scss
arcgis defines its own font-family for :root (html). In order to reliably overwrite any other definition, we have added !important to the font-family.
> fix: ensure correct font-family

- src/angular/table/sort/sort-header.ts
- src/angular/table/sort/sort.spec.ts
- src/angular/table/table.md
- src/components-examples/angular/table/filter-sort-paginator-table/filter-sort-paginator-table-example.html
- src/components-examples/angular/table/filter-sort-paginator-table/filter-sort-paginator-table-example.ts
- src/components-examples/angular/table/sortable-table/sortable-table-example.html
- src/components-examples/angular/table/sortable-table/sortable-table-example.ts
- src/components-examples/angular/table/sticky-table/sticky-table-example.html
- src/components-examples/angular/table/sticky-table/sticky-table-example.ts
Adds a description input for sbb-sort-header so that developers can provide an accessible description (using AriaDescriber under the hood). Additionally, update the accessibility section for the sort header's documentation with guidance on providing an accessible experience.
We decided to use this approach because the message developers would want to set here depends on several bits of information, including:
* Whether the column is currently sorted
* The sort direction
* Whether users can clear sorting (configured on `SbbSort`)
* The name of the column (not the ID)
Accounting for all of these factors would have made the intl formatting too complicated. This does have the negative consequence of needing to set a description for every header. However, users can add a custom directive to …
> fix: add description input for sort-header

- src/angular/tooltip/tooltip.ts
Previously the tooltip would close when it clipped the scrollable
context/parent. This would lead to the tooltip immediately closing on
scrolling when above such a border. This PR changes this behavior to
only close the tooltip when the origin of the tooltip is scrolled outside
the view.
> fix: avoid closing tooltip on clipping parent container

- src/angular/core/option/option.ts
Makes `SbbOption` generic so that consumers can type its `value` to something different from `any`.
https://github.com/angular/components/pull/20242
> fix(angular/core): make SbbOption generic

- src/angular/input/input.ts
If an input has a `name` binding and an `ngModel`, the input harness won't be able to
read the name from the DOM, because `ngModel` doesn't proxy it. These changes add
the proxy behavior to the `SbbInput` directive, similarly to what we we're doing for
`required`, `placeholder`, `readonly` etc.
https://github.com/angular/components/pull/19233
> refactor(angular/input): inconsistently reading name from input with ngModel

- src/angular/autocomplete/autocomplete-trigger.ts
- src/angular/autocomplete/autocomplete.spec.ts
Doesn't handle `ENTER` key presses and doesn't prevent their default action,
if they have a modifier, in order to avoid interfering with any OS-level shortcuts.
https://github.com/angular/components/pull/14717
> fix(angular/autocomplete): don't handle enter events with modifier keys

- src/angular/table/table.spec.ts
- src/angular/table/table/table-data-source.ts
The table data source is set up to expect an array and will throw a cryptic error
down the line if the value is anything different. While typings should be enough to enforce this,
if the value comes from somewhere in the view it may not get caught.
Since the effort for handling it on our end is minimal,
these changes add some logic that fall back to an empty array if the value is invalid.
https://github.com/angular/components/pull/18953
> fix(angular/table): better handling of invalid data

- src/angular/sidebar/icon-sidebar/icon-sidebar-container.html
- src/angular/sidebar/icon-sidebar/icon-sidebar.ts
- src/angular/sidebar/sidebar/sidebar-container.html
- src/angular/sidebar/sidebar/sidebar.ts
When the consumer doesn't provide a `sbb-sidebar-content`, we create one implicitly for them.
The implicit content element has a `cdkScrollable` on it, which means that it'll be
registered on the `ScrollDispatcher` as a `CdkScrollable`, however since `SbbSidebarContent`
also extends `CdkScrollable`, it'll be registered again as a `SbbSidebarContent`.
These change remove the extra `cdkScrollable` from the view in order to avoid the issue.
These changes also provide the sidenav content as a `CdkScrollable` for DI purposes.
https://github.com/angular/components/pull/13973
> fix(angular/sidebar): implicit content element being registered twice with scroll dispatcher

- src/angular/autocomplete/autocomplete-trigger.ts
- src/angular/autocomplete/autocomplete.spec.ts
Fixes the `SbbAutocompleteTrigger.optionSelections` stopping to emit when
the list options has been swapped out.
https://github.com/angular/components/issues/14777
> fix(angular/autocomplete): optionSelections not emitting when the list of options changes

- src/angular/tooltip/tooltip.spec.ts
- src/angular/tooltip/tooltip.ts
Currently, the tooltip's `keydown` handler is on the trigger, which means that it won't fire
if the trigger doesn't have focus. This could happen when a tooltip was opened by
hovering over the trigger. These changes use the `OverlayKeyboardDispatcher` to
handle the events instead.
https://github.com/angular/components/pull/14434
> fix(angular/tooltip): not closing if escape is pressed while trigger isn't focused

- src/angular/chips/chip-input.ts
It is initialized in the constructor, so there is no chance of it being
undefined.
https://github.com/angular/components/pull/23868
> fix(angular/chips): declare that SbbChipInput.inputElement is always defined

- src/angular/badge/badge.spec.ts
- src/angular/badge/badge.ts
- src/angular/tag/tags.spec.ts
Previously, `SbbBadge` was applying the provided description
as an `aria-label` to the badge content element, which is
a child element of the badge host. Then it was _also_ applying
an `aria-describedby` to that same content element.
The end result is that the badge was being treated
mainly as text content for a control, which isn't really
the best way to convey its complementary nature.
This behavior was causing problems in NVDA,
where the badge content was overriding the host button's label.
This change makes the badge content itself `aria-hidden` and
applies the badge description to the badge's _host_ element
via `aria-describedby` and completely removes any setting of `aria-label`.
It also makes a handful of minor cleanup refactorings.
https://github.com/angular/components/pull/23562
> fix(angular/badge): correctly apply badge description

- src/angular/sidebar/sidebar-base.ts
- src/angular/sidebar/sidebar/sidebar.ts
Currently, when a sidebar is closed, we restore the focus origin as when it was focused
because we don't know what kind of event closed it, however if it happens through
the backdrop, we can be fairly certain that it was via mouse.
These changes pass in the `mouse` origin when closing through the backdrop.
https://github.com/angular/components/pull/23492
> fix(angular/sidebar): restore focus with correct origin when closing via the backdrop

- src/angular/autocomplete/autocomplete.spec.ts
- src/angular/autocomplete/autocomplete.ts
Fixes that we were emitting the `optionActivated` event when the option is
reset programmatically when the panel closes.
The intent was to only emit the event as a result of a user action.
https://github.com/angular/components/pull/23437
> fix(angular/autocomplete): don't emit optionActivated event when option is reset

- src/angular/icon/icon-registry.ts
- src/angular/icon/trusted-types.ts
When SBB Angular is used in an environment that enforces Trusted
Types, the icon registry raises a Trusted Types violation due to its use
of element.innerHTML when initializing SVG icons.
To make the icon registry compatible with Trusted Types,
SvgIconConfig.svgText is changed to a TrustedHTML, and its users updated
to either produce TrustedHTML (making sure to only do so in cases where
its security can be readily assessed) or pass such values along.
To facilitate this, add a module that provides a Trusted Types policy,
'sbb-esta#angular'. The policy is created lazily and stored in a
module-local variable. This is the same as the approach taken by Angular
proper in
https://github.com/angular/angular/blob/master/packages/core/src/util/security/trusted_types.ts
> fix(angular/icon): make icon-registry compatible with Trusted Types

- src/angular/select/select/select.spec.ts
- src/angular/select/select/select.ts
Fixes the `SbbSelect.value` property not being in sync
with the `ControlValueAccessor` initial value on init.
https://github.com/angular/components/pull/18443
> fix(angular/select): component value not in sync with control value on init

- package.json
With this change we remove the lines length restriction in commit message body. This was previously in place due to a bug in GitHub UI, which is now fixed.
> build: remove commit message max line length limit

- src/angular/autocomplete/autocomplete-trigger.ts
- src/angular/autocomplete/autocomplete.spec.ts
Currently, we restore focus to the input and then we emit the change event, but we have a report that it may be making some use cases more difficult. From what I can tell, this shouldn't have much of an impact on existing users so these changes swap the order so that the focus event is last.
https://github.com/angular/components/commit/7409bd615f63a0a5d2c2ccee9ce278b0cce6bb69
> fix(angular/autocomplete): restore focus after emitting option selected event

- src/angular/radio-button/radio-button.ts
- src/angular/styles/_typography.scss
Previously we would show error styles, when any ancestor had .ng-touched.ng-invalid assigned.
This could also be the FormGroup element, which would cause the radio-button-panel
to incorrectly be marked as invalid.
Closes #1078
> fix(angular/radio-button-panel): only show error styles when parent group is invalid

- src/angular/package.json
Adds the `exports` field for module resolution of `@sbb-esta/angular` when Sass is requested.
Since these packages use the `exports` field already, to prevent
deep imports, we also need to expose the Sass entry-points and prebuilt
files. The webpack loader requires the `sass` conditional to be set
when the sbb-angular modules are loaded without the `includePaths` option.
> build: add `exports` entries for Sass module resolution

- src/angular/search/search.scss
Previously the shadow was only shown below the input, but not the button.
We now apply the shadow to the `sbb-search`.
> fix(angular/search): show the autocomplete shadow along the entire width

- src/angular/chips/chip.ts
Historically we've had to stop propagation on clicks so that clicking on a chip won't move focus to the first chip once the event bubbles up to the list. This isn't necessary because we changed how we detect clicks from inside a chip. These changes remove the call since it can prevent people's global click listeners from firing.
> fix(angular/chips): don't stop propagation on all click events

- src/angular/table/table.md
On some examples, the closing tag for sbb-table-wrapper is a div instead of sbb-table-wrapper
> docs(table): correct closing tag

- src/angular/tabs/tab-body.scss
- src/angular/tabs/tab-body.ts
- src/angular/tabs/tab-config.ts
- src/angular/tabs/tab-group.html
- src/angular/tabs/tab-group.spec.ts
- src/angular/tabs/tab-group.ts
- src/angular/tabs/tabs-animations.ts
- src/angular/tabs/tabs.md
- src/components-examples/angular/tabs/index.ts
- src/components-examples/angular/tabs/tab-group-preserve-content/tab-group-preserve-content-example.html
- src/components-examples/angular/tabs/tab-group-preserve-content/tab-group-preserve-content-example.ts
Adds the `preserveContent` input which allows consumers to opt into keeping the content of off-screen tabs inside the DOM. This is useful primarily for edge cases like iframes and videos where removing the element from the DOM will cause it to reload.
One gotcha here is that we have to set `visibility: hidden` on the off-screen content so that users can't tab into it.
https://github.com/angular/components/commit/cad087220848b2cd2c252520bac26a42d8b279aa
> feat(angular/tabs): add the ability to keep content inside the DOM while off-screen

- src/angular/tabs/tab-header.html
- src/angular/tabs/tab-nav-bar.html
Uses `button` elements, rather than styled `div`-s for the paginator buttons. This has the advantage of being more accessible, if we decided to make them focusable, and it stops calling the click listeners when the button is disabled (currently we do some expensive checks in them when we don't have to).
> fix(angular/tabs): use buttons for paginator

- src/angular/datepicker/calendar-body/calendar-body.html
- src/angular/datepicker/calendar-body/calendar-body.spec.ts
- src/angular/datepicker/datepicker-content/datepicker-content.scss
Makes changes to the DOM structure of calendar cells for better screen reader experience. Previously, the DOM
structure looked like this:
```
<td
class="sbb-calendar-body-cell"
role="gridcell"
aria-disabled="false"
aria-current="date"
aria-selected="true"
>
</>
```
Using the `gridcell` role allows screenreaders to use table specific
navigation and some screenreaders would announce that the cells are
interactible because of the presence of `aria-selected`. However, some
screenreaders did not announce the cells as interactable and treated it
the same as a cell in a static table (e.g. VoiceOver announces element
type incorrectly angular/components#23476).
This changes the DOM structure to nest buttons
inside of a gridcell to make it more explicit that the table cells can
be interacted with …
> fix(angular/datepicker): change calendar cells to buttons

- src/angular/input/input.spec.ts
- src/angular/select/select/select.spec.ts
- src/angular/sidebar/icon-sidebar/icon-sidebar.spec.ts
- src/angular/sidebar/sidebar/sidebar.spec.ts
- yarn.lock
The workarounds shouldn't be necessary since we don't run tests against IE and legacy Edge anymore.
> test: clean up IE/Edge test workarounds

- src/angular/datepicker/datepicker/datepicker.ts
- src/angular/radio-button/radio-button.ts
- src/angular/tabs/paginated-tab-header.ts
- src/angular/tabs/tab-group.ts
- src/angular/tabs/tabs.md
- src/angular/textarea/textarea/textarea.ts
- src/angular/tooltip/tooltip.ts
- src/components-examples/angular/tabs/tab-group-preserve-content/tab-group-preserve-content-example.html
Previously, some properties were declared as BooleanInput and some not. With this commit, all boolean inputs are threat as BooleanInput and therefore the input values are being coerced.
> fix(angular): allow coercing of booleans for all inputs

- src/angular/datepicker/BUILD.bazel
- src/angular/datepicker/date-input/date-input.directive.ts
- src/angular/datepicker/datepicker-content/datepicker-content.html
- src/angular/datepicker/datepicker-content/datepicker-content.ts
- src/angular/datepicker/datepicker/datepicker.spec.ts
- src/angular/datepicker/datepicker/datepicker.ts
Fixes focus trapping on the datepicker dialog by putting `role="dialog"` `aria-modal="true"` and `cdkTrapFocus` all on the same element. This aligns the datepicker with how SbbDialog does focus trapping.
Without having them all on the same element, users could exit out of the focus trapping using screenreader specific navigation with VoiceOver and ChromeVox.
> fix(angular/datepicker): fix improper focus trapping with VoiceOver and ChromeVox

- src/angular/form-field/form-field.scss
- src/angular/styles/_typography.scss
> fix(angular/form-field): allow sbb-error styling to be used outside sbb-form-field

- src/angular/datepicker/calendar-body/calendar-body.html
- src/angular/datepicker/calendar-body/calendar-body.ts
- src/angular/datepicker/month-view/month-view.html
- src/angular/datepicker/month-view/month-view.spec.ts
- src/angular/datepicker/month-view/month-view.ts
When a date cell on the calendar recieves focus, set the active date to that cell. This ensures that the active date matches the date with browser focus.
Previously, we set the active date on keydown and click, but that was problematic for screenreaders. That's because many screenreaders trigger a focus event instead of a keydown event when using screenreader specific navigation (VoiceOver, Chromevox, NVDA).
> fix(angular/datepicker): update active date on focusing a calendar cell

- src/angular/menu/menu-trigger.ts
- src/angular/menu/menu.spec.ts
- src/angular/menu/menu.ts
We were calling `SbbMenu.setPositionClasses` in order to set the classes if the position changes, but the call was outside of the `NgZone` so nothing was happening. These changes bring the call back into the `NgZone`.
> fix(angular/menu): position classes not updated when window is resized

- src/angular/sidebar/sidebar.module.ts
The `PlatformModule` is a noop, so we don't need to import it.
> refactor(angular/sidebar): remove PlatformModule usage

- src/angular/chips/chip-list.ts
Fixes ExpressionChangedAfterItHasBeenCheckedError that occurs when chip-lists are content-projected into a sbb-form-field
> fix(angular/chips): update chip-list describedby to match input

- package.json
- scripts/run-component-tests.js
- tools/defaults.bzl
- yarn.lock
We recently moved the karma web test suite debug tooling to
the dev-infra repository, allowing for the code to be used in
framework as well. This dedupes the logic in the COMP repo.
> build: use shared karma web test suite from dev-infra

- package.json
- src/angular/styles/_typography.scss
Fixes a regression caused by #1172 where clicking directly on the `input` element will prevent the click from reaching custom `click` listeners outside the radio button.
> fix(angular/radio-button): clicks not propagating to wrapper elements

- src/angular/autocomplete/autocomplete-trigger.ts
- src/angular/autocomplete/autocomplete.spec.ts
[Based on the spec](https://www.w3.org/TR/wai-aria-1.1/#aria-haspopup),
`aria-haspopup` can be set to indicate what kind of popup the element has.
These changes update the autocomplete one to show that it opens a listbox.
> fix(angular/autocomplete): use narrow value for aria-haspopup

- src/angular/sidebar/sidebar/sidebar.scss
- src/angular/tabs/tab-body.scss
This is a similar fix that we've made for other components. Usually we set `visibility: hidden` on the sidebar which is enough to prevent the user from tabbing into it, however one of the children could override it with `visibility: visible`. These changes add an extra `display: none` on top which will prevent such issues. This has come up on AIO recently angular/angular#44990.
> fix(angular/sidebar): prevent focus from entering hidden sidenav if child element has a visibility

- src/angular/autocomplete/autocomplete-trigger.ts
- src/angular/autocomplete/autocomplete.spec.ts
Currently, we hijack all up/down arrow key events, however this interferes with keyboard shortcuts such as shift + up arrow for marking all of the text. These changes stop intercepting the arrow keys, if they're used with a modifier.
These changes also fix an issue where all the mocked out key events had the `metaKey` set to `true` on some browsers.
> fix(angular/autocomplete): don't block default arrow keys when using modifiers

- src/angular/table/sort/sort-header.html
- src/angular/table/sort/sort-header.ts
- src/angular/table/sort/sort.spec.ts
When the sort header is disabled, we make it non-interactive by clearing its `tabindex`, however it still has the `role="button"` which can throw off screen readers if it doesn't have text.
These changes also clear the `role` from the header if it's disabled.
> fix(angular/table): remove role from sort header when disabled

- src/angular/autocomplete/autocomplete-trigger.ts
- src/angular/autocomplete/autocomplete.spec.ts
- src/angular/autocomplete/autocomplete.ts
Adds the `autoSelectActiveOption` input to `sbb-autocomplete` which allows the
consumer to opt into the behavior where the autocomplete will assign the active
option value as the user is navigating through the list. The value is only propagated
to the model once the panel is closed.
There are a couple of UX differences when the new option is enabled:
1. If the user presses escape while there's a pending auto-selected option, the value
is reverted to the last text they typed before they started navigating.
2. If the user clicks away, tabs away or presses enter while there's a pending option,
it will be selected.
The aforementioned UX differences are based on the Google search autocomplete and
one of the examples from the W3C here: …
> feat(angular/autocomplete): add the ability to auto-select the active option while navigating

- src/angular/tooltip/tooltip.scss
- src/angular/tooltip/tooltip.spec.ts
- src/angular/tooltip/tooltip.ts
Currently, we hide the tooltip as soon as the pointer leaves the trigger element which may be problematic with larger cursors that partially obstruct the content.
These changes allow hover events on the tooltip and add extra logic so that moving to it doesn't start the hiding sequence.
> fix(angular/tooltip): don't hide when pointer moves to tooltip

- src/angular/autocomplete/autocomplete-trigger.ts
- src/angular/autocomplete/autocomplete.spec.ts
Currently, if the user clicks an autocomplete to open it, selects an option and then clicks again, the panel won't open, because we use `focus` and the input was focused already. These changes add an extra `click` listener so the panel can reopen.
> fix(angular/autocomplete): reopen panel on input click

- src/angular/schematics/ng-add/index.spec.ts
- src/angular/schematics/ng-add/schema.json
- src/angular/schematics/ng-add/schema.ts
- src/angular/schematics/ng-add/setup-project.ts
Adds a third option to the `ng-add` schematic that allows users to opt out of including any of the animations modules.
> feat(angular/schematics): add option not to include animations module in ng-add

- src/angular/icon/icon-registry.ts
- src/angular/icon/icon.spec.ts
- src/angular/icon/icon.ts
- src/angular/icon/testing/fake-icon-registry.ts
Allows for the consumer to pass in multiple classes to `SbbIconRegistry.setDefaultFontSetClass`.
> feat(angular/icon): allow multiple classes in setDefaultFontSetClass

- src/angular/menu/menu-item.ts
- src/angular/menu/menu.spec.ts
- src/angular/menu/menu.ts
Fixes the user's focus being lost if the active item is destroyed while a menu is open.
See https://stackblitz.com/edit/angular-v1c2k9?file=src%2Fapp%2Fmenu-overview-example.ts
> fix(angular/menu): focus lost if active item is removed

- src/angular/datepicker/calendar/calendar-header.html
On the period button on the calendar, use `aria-live` over `cdkAriaLive` because that seems to work better with VoiceOver. This fixes an issue where VoiceOver did not announce the month after clicking the "Month" / "Previous Month" buttons
> fix(angular/datepicker): use aria-live over cdkAriaLive on period button

- src/angular/dialog/dialog.ts
Currently the `ComponentFactoryResolver` from the dialog config is only used for the dialog container. These changes switch to also use it for the dialog content component.
> fix(angular/dialog): use passed in ComponentFactoryResolver to resolve dialog content

- src/angular/button/button.spec.ts
- src/angular/button/button.ts
Fixes that the button component was always setting a `tabindex="0"` when it's placed on a link element. This is unnecessary, because links are in the tab order by default.
We actually had a test that has an assertion against this, but it was passing by accident because we weren't running change detection before making the asserting.
> fix(angular/button): avoid setting a tabindex on all link buttons

- src/angular/styles/_typography.scss
When hovering over an autocomplete item, the `strong` part does not change its color. This is because the selector `.sbb-menu-item:is(:hover strong)` did not select the `strong` tag.
> fix(angular/autocomplete): correct color of hover elements

- src/angular/accordion/expansion-panel.scss
The expansion panel sets `visibility: hidden` while it's closed in order to prevent users from tabbing into the content. This breaks down if a child has its own `visibility`, because it overrides the one coming from the parent. We can't use `display` in the animation definition, because it prevents the animations module from calculating the height when animating.
> fix(angular/autocomplete): able to tab into descendants with visibility while closed

- src/angular/chips/chip-input.ts
- src/angular/chips/chip-list.spec.ts
- src/angular/chips/chip.ts
Before this change the chip control modified the underlying array or set instance in place. This led to unexpected behaviour, e.g. when used with `distinctUntilChanged((prev, curr) => prev === curr)` (where `prev` and `curr` point to the same array). Therefore, we now return a new array or set instance after a chip was removed or added.
> fix(angular/chips): create new array or set on update

- src/angular/dialog/dialog-config.ts
- src/angular/dialog/dialog-container.ts
This adds the new dialog parameter `delayFocusTrap`. Main purpose of the PR is to keep in sync with angular/components
> fix(angular/dialog): don't wait for animation before moving focus

- src/angular/tabs/paginated-tab-header.ts
- src/angular/tabs/tab-header.spec.ts
The tabs have a couple of `requestAnimationFrame` calls when checking for the size/position of elements which can cause tests to hang when they're in a background tab. The problem is that browsers block `requestAnimationFrame` when the browser is out of focus and test harnesses will wait for the call to resolve.
These changes switch to `NgZone.onStable` in an attempt to resolve the issue.
Moreover, remove a duplicate test.
> fix(angular/tabs): avoid timeouts in background tabs

- src/angular/icon/icon.scss
Clips any elements that are overflowing an icon. This avoids issues where parts of the icon could stick out and layouts.
> fix(angular/icon): clip overflowing icon elements

- src/angular/dialog/dialog-animations.ts
- src/angular/dialog/dialog-config.ts
- src/angular/dialog/dialog-container.ts
- src/angular/dialog/public-api.ts
Even though we provide defaults when we construct the animation object, some internal cases break because there are no defaults in the animation definition itself. These changes provide the defaults in the animation definition as well.
> fix(angular/dialog): provide defaults for dialog animation

- src/angular/datepicker/calendar-body/calendar-body.ts
- src/angular/datepicker/datepicker/datepicker.spec.ts
Add a timeout before programmatically focusing cells on the calendar. This seems to fix an issue where Voiceover loses focus when pressing the PageDown/PageUp keys.
> fix(angular/datepicker): fix Voiceover losing focus on PageDown

- src/angular/autocomplete/autocomplete-trigger.ts
The `NgZone.onStable` always emits outside of the Angular zone, but the zone has not been
re-entered. This leads to change detection being called outside of the Angular zone and the
`autocomplete.opened` also was emitting values outside of the Angular zone.
> fix(angular/autocomplete): re-enter the Angular zone when the `NgZone.onStable` emits

- src/angular/schematics/ng-add/migrations/merge-refactor/badge-migration.ts
- src/angular/schematics/ng-add/migrations/merge-refactor/processflow-migration.ts
- src/angular/schematics/utils.ts
- tools/dgeni/processors/entry-point-grouper.ts
- tools/markdown-to-html/docs-marked-renderer.ts
- tools/region-parser/region-parser.ts
.substr() is deprecated, so we replace it with .slice() which works similarly but isn't deprecated
> refactor: replace deprecated String.prototype.substr()

- src/angular/dialog/dialog-animations.ts
- src/angular/dialog/dialog-config.ts
- src/angular/dialog/dialog-container.ts
- src/angular/dialog/public-api.ts
- src/angular/lightbox/lightbox-animations.ts
- src/angular/lightbox/lightbox-config.ts
- src/angular/lightbox/lightbox-container.ts
- src/angular/lightbox/public-api.ts
- src/components-examples/angular/dialog/dialog-animations/dialog-animations-example.css
- src/components-examples/angular/dialog/dialog-animations/dialog-animations-example.html
- src/components-examples/angular/dialog/dialog-animations/dialog-animations-example.ts
- src/components-examples/angular/dialog/index.ts
- src/components-examples/angular/lightbox/index.ts
- src/components-examples/angular/lightbox/lightbox-animations/lightbox-animations-example.css
- src/components-examples/angular/lightbox/lightbox-animations/lightbox-animations-example.html
- src/components-examples/angular/lightbox/lightbox-animations/lightbox-animations-example.ts
Since the dialog animation is on the `SbbDialogContainer`, consumers aren't able to disable the animation. These changes add properties to the dialog config that allow consumers to set the duration of the dialog's enter and exit animations.
**Memo**: Merge #1287 first
> feat(angular/dialog): add the ability to control the animation duration

- src/angular/select/select.spec.ts
- src/angular/select/select.ts
Fixes values set through the `value` property not being propagated to the `value` in the `ControlValueAccessor`.
> fix(angular/select): value set through property not being propagated to value accessor

- src/angular/form-field/form-field-control.ts
- src/angular/form-field/form-field.ts
Allows for an `AbstractControlDirective` to be passed in as the `SbbFormFieldControl.ngControl`. The advantage of passing in the abstract control directive is that it allows both form controls and form groups. This is necessary for the date range picker.
> refactor(angular/form-field): allow AbstractControlDirective as MatFormFieldControl.ngControl

- src/angular/autocomplete/autocomplete-trigger.ts
- src/angular/autocomplete/autocomplete.spec.ts
This PR ensures that the `closed` event is emitted after the panel was closed by entering a string that did not match any option.
Closes #1274
> fix(angular/autocomplete): always emit closed event

- src/angular/tabs/tab-group.spec.ts
- src/angular/tabs/tab-group.ts
Currently, the `tabindex` of each of the tab labels is determined by the selected index. This means that if the user tabbed into the header, pressed the right arrow and then pressed shift + tab, their focus would end up on the selected tab. These changes switch to basing the `tabindex` on the focused index which is tied both to the selected index and the user's keyboard navigation.
> fix(angular/tabs): focus wrapping back to selected label when using shift + tab

- src/angular/radio-button/radio-button.spec.ts
- src/angular/radio-button/radio-button.ts
Currently all radio buttons inside a radio group have a `tabindex` of 0,  unless they're disabled, and we leave it up to the browser to focus the proper button based on its selected state when the user is tabbing. This works for the most part, but it breaks down with something like our focus trap which determines which element to focus based on its `tabindex` since all buttons have the same `tabindex`. These changes fix the issue by setting a `tabindex` of 0 only on the selected radio button.
> fix(angular/radio): set tabindex based on selected state

- src/angular/tabs/paginated-tab-header.ts
- src/angular/tabs/tab-header.spec.ts
Fixes the case where the user has scrolled to the end of the tab list and the selected tab from the beginning is removed. Since we no longer have a selected tab, the scroll distance wasn't being updated.
> fix(angular/tabs): wrong scroll distance if selected tab is removed

- src/angular/datepicker/calendar/calendar.spec.ts
- src/angular/datepicker/calendar/calendar.ts
Avoid re-rendering when the [minDate] or [maxDate]
Input change to a different time on the same day.
In ngOnChanges, do not call init if the previous and current value for
minDate/maxDate are on the same day.
> fix(angular/datepicker): avoid rerender when min/maxDate changes to different time on the same day

- src/angular-experimental/schematics/BUILD.bazel
- src/angular/schematics/BUILD.bazel
As part of v13, we manually added the prodmode/devmode target to schematic
build targets and set it to `es2015`. This was done since we still supported
NodeJS v12. This is no longer the case with v14 and we already removed the
NodeJS v12 integration test, so we can also remove the target override.
> build: ship schematics as es2020 similar to rest of the APF

- src/angular/dialog/dialog-content-directives.ts
- src/angular/dialog/dialog.ts
- src/angular/lightbox/lightbox.spec.ts
Previously we had to walk the DOM in order to figure out which dialog ref belonged to a specific template dialog. We no longer need to do that if we provide an injector to the template portal.
> refactor(angular/dialog): use embedded injector to provide ref to template dialogs

- src/angular/chips/chip-list.ts
- src/angular/core/common-behaviors/error-state.ts
- src/angular/input/input.ts
- src/angular/select/select.ts
- src/angular/textarea/textarea/textarea.ts
The error state mixin provided in `@sbb-esta/angular/core` currently
defines the `stateChanges` class member as part of the mixin. This
is unexpected as consumers might deal with the `stateChanges` member
differently. e.g. in some components the `stateChanges` field is
intended to show up in the docs, or the JSDoc description varies. e.g.
the observable could emit whenever form-field state changes, and it
should be updated, or it emits always when something changes (e.g.
even a component input which is not relevant for the form-field
control).
In general, we want to avoid this member being defined in the mixin
as the mixin is rather about the error state, and not defining a
subject that can emit whenever "state" changes.
BREAKING CHANGE: Previously the `mixinErrorState` mixin function …
> refactor(angular/core): no longer define stateChanges in `mixinErrorState`

- src/angular/schematics/ng-add/migrations/secondary-entry-points-migration.ts
Removes our compatibility code for TypeScript less than 4.6.
> build: drop support for TypeScript less than 4.6

- src/angular/autocomplete/autocomplete-trigger.ts
- src/components-examples/angular/autocomplete/autocomplete-option-group/autocomplete-option-group-example.ts
Previously we called clean-up (and option highlighting) on each zone.js
onStable emit. This caused a near constant loop of the functionality
being called on large applications. We fixed this by limiting the call
to just the next onStable emit and removing it entirely for the clean-up
as it is not necessary there.
> fix(angular/autocomplete): prevent clean-up from repeatedly being called

- src/angular/chips/chip-remove.spec.ts
- src/angular/chips/chip.ts
- src/angular/input/BUILD.bazel
Adds a `preventDefault` call to the `click` handlers of the chip remove icon in order to avoid things like form submissions and link navigations.
> fix(angular/chips): prevent default behavior on remove button

- src/angular/autocomplete/autocomplete-trigger.ts
- src/angular/autocomplete/autocomplete.spec.ts
Fixes a bug in `autocomplete` when outside click doesn't trigger `changeDetection`.
> fix(angular/autocomplete): outside click in Angular zone

- src/showcase/assets/BUILD.bazel
The StackBlitz examples are not working anymore due to the journey-maps integration. Since journey-maps does not use StackBlitz, the integration is removed by this PR.
> fix: make stackblitz examples working again

- src/angular/menu/menu-item.ts
- src/angular/schematics/ng-add/data/constructor-checks.ts
Order of constructor parameters of `SbbMenuItem` has been changed and made required.
> refactor(angular/menu): make parameters required in constructor of SbbMenuItem

- src/angular/menu/menu.ts
When opening the menu using the iOS VoiceOver screen reader, focus the first item in the menu.
Previously, the first menu item would focus on other screen readers like desktop VoiceOver but
not with iOS VoiceOver.
Waiting until `onStable` seems to fix this.
> fix(angular/menu): focus the first item when opening menu on iOS VoiceOver

- src/angular/datepicker/date-input/date-input.directive.ts
Shows valid formatted value for 'falsy' values (exp 0)
Custom DateAdapter (exp TimestampDateAdapter) can have valid numeric 0 value (for timestamp it is 1/1/1970), but datepicker input doesn't show formatted value
> fix(angular/datepicker): add ability to have numeric zero value in input

- src/angular/select/select.html
Screen readers announce the selected value multiple times. NVDA e.g. reads "Favorite food Pizza Pizza combobox Pizza collapsed".
1. First, the Screen Reader (SR) reads the value of the label (see 1st `aria-labelledby`): "Favorite food"
2. SR reads the content of the combobox: "Pizza"
3. SR reads the value of the combobox (see 2nd `aria-labelledby`): "Pizza"
4. SR reads the content of the combobox again: "Pizza"
To fix this, an `aria-hidden` attribute is added to the element containing the selected value. NVDA e.g. now reads "Favorite food Pizza combobox collapsed".
Successfully tested with NVDA, JAWS, Narrator and the _Screen Reader_ Chrome plugin.
Closes #1385
> fix(angular/select): don't announce selected value multiple times

- renovate.json
angular-t9n does not provide update schematics and therefore `ng update` fails.
> chore: remove angular-t9n from renovate ng update

- RELEASE.md
- src/angular/button/button.ts
- src/angular/datepicker/datepicker/datepicker.ts
- src/angular/loading/loading-indicator.ts
- src/angular/schematics/ng-update/data/constructor-checks.ts
- SbbAnchor: Constructor parameter `ngZone` has become required.
- SbbDatepicker: Remove unused constructor parameter `document`.
> refactor: remove various deprecations

- src/angular/tooltip/tooltip.spec.ts
- src/angular/tooltip/tooltip.ts
> fix(angular/tooltip): stop event propagation on trigger click

- src/angular/core/common-behaviors/error-state.ts
- src/angular/processflow/processflow.ts
Accept AbstractControl instead of FormControl to avoid compiler errors when strict typing is enabled
> fix(angular/processflow): accept AbstractControl in isErrorState

- src/angular/dialog/dialog-content-directives.ts
- src/angular/i18n/xlf/messages.xlf
- src/angular/i18n/xlf2/messages.xlf
- src/angular/lightbox/lightbox-content-directives.ts
Global $localize usage would be called before our $localize monkey
patch. Inlining the $localize call causes a slight duplication, but this
should be acceptable at this scale.
> fix: remove global $localize usage

- src/showcase/app/howtoupdate/update-steps.ts
Due to https://github.com/angular/angular-cli/issues/22654 the migration from version 12 to version 13 does not work properly. To circumvent the bug `@angular-devkit/build-angular@13` is updated separately with a fixed version.
> docs: update steps for v13 migration

- src/angular/autocomplete/autocomplete-trigger.ts
- src/angular/autocomplete/autocomplete.spec.ts
Closes #1571
Fix to avoid scrolling to the top if a new element is added. This happens because our overlay has a dynamic height (different from @angular/material).
When the _resetBoundingBoxStyles() function in the FlexibleConnectedPositionStrategy is called, the element is reset to full height and scaled back afterwards. When scaling back the scroll position gets lost.
An alternative to this hack would be to either use a maxHeight property for our overlay or to fix this in angular/components.
> fix(angular/autocomplete): do not reset scroll if an option is added

- package.json
- renovate.json
- yarn.lock
This is necessary due to a mysterious build bug.
> ci: pin rxjs and @types/geojson deps

- src/angular/autocomplete/autocomplete-trigger.ts
Adds a subscription to the outside click stream of the autocomplete overlay so that the events don't propagate to other overlays which may close the autocomplete prematurely.
> fix(angular/autocomplete): prevent outside clicks from going to other overlays

- src/angular/core/datetime/date-formats.ts
- src/angular/core/datetime/date-pipe-date-formats.ts
- src/angular/datepicker/date-input/date-input.directive.ts
- src/angular/datepicker/datepicker/datepicker.spec.ts
Don't display the name of the weekday if `SbbDateInput` is used without `SbbDatePicker`.
Closes #1610
> fix(angular/datepicker): no weekday in standalone date input

- src/angular/schematics/ng-add/setup-project.ts
The standalone utilities were copied into `@schematics/angular` so that they can be reused.
> refactor(angular/schematics): reuse standalone component utilities

- src/angular/lightbox/lightbox-container.ts
- src/angular/lightbox/lightbox.scss
- src/angular/lightbox/lightbox.spec.ts
- src/angular/lightbox/lightbox.ts
Use `window.innerHeight` instead of `100vh` to calculate the height of the `SbbLightBox`.  This is necessary because on mobile Chrome and Safari, `100vh` includes the address bar and is therefore taller than the actual viewport (see e.g. [this explanation](https://bugs.webkit.org/show_bug.cgi?id=141832#c5)). This led to cut off buttons in the lightbox.
Closes #1586
> fix(angular/lightbox): fix height calculation on mobile

- src/angular/checkbox-panel/checkbox-panel.html
- src/angular/checkbox-panel/checkbox-panel.md
- src/angular/checkbox-panel/checkbox-panel.spec.ts
- src/angular/radio-button-panel/radio-button-panel.html
- src/angular/radio-button-panel/radio-button-panel.md
- src/angular/radio-button-panel/radio-button-panel.spec.ts
According to the specification, div containers are not allowed inside labels.
Closes #1619
> fix(multipe): don't use div containers inside labels

- src/angular/processflow/processflow.html
- src/angular/processflow/processflow.spec.ts
The `aria-expanded` attribute is not valid for the `tabpanel` role (see e.g. [here](https://www.w3.org/TR/wai-aria-1.2/#tabpanel)). It can be simply removed because selecting the tab with `aria-selected` in combination with an `aria-controls` pointing to the `tabpanel` is already enough.
Closes #1613
> fix(angular/processflow): remove obsolete aria-expanded attribute

- src/angular/loading-indicator/loading-indicator.md
- src/components-examples/angular/loading-indicator/loading-indicator-fullbox/loading-indicator-fullbox-example.html
- src/components-examples/angular/loading-indicator/loading-indicator-inline/loading-indicator-inline-example.html
- src/components-examples/angular/loading-indicator/loading-indicator-simple/loading-indicator-simple-example.html
Add an accessibility section to the loading indicator docs. Obsolete `aria-valuetext` attributes are removed.
Closes #1634
> docs(angular/loading-indicator): add accessibility section

- src/angular/notification/notification.md
Add an accessibility section to the docs of `sbb-notification` and update the documentation for `types`.
Closes #1635
> docs(angular/notification): add accessibility section

- src/angular/tooltip/tooltip.ts
This reverts commit 603726eb804c56033ffab3ea9787f8048903884e.
This introduced a race condition which caused tooltips to get stuck in the DOM in an invisible state.
> Revert "fix(angular/tooltip): avoid problem when triggers hide animation for not visible tooltip"

- renovate.json
Ignoring them was done due to a build bug (see #1609). However, it turned out they're not responsible for this bug.
> ci: allow renovate to update @types/geojson and rxjs

- src/angular/dialog/dialog-config.ts
- src/angular/dialog/dialog-container.ts
- src/angular/dialog/dialog.spec.ts
- src/angular/lightbox/lightbox-config.ts
- src/angular/lightbox/lightbox-container.ts
- src/angular/lightbox/lightbox.spec.ts
Fixes that `aria-modal` wasn't being set on the dialog container. This likely got broken when the dialog was changed to be based on top of the CDK dialog.
The `ariaModal` option is added to the config to avoid that it's overridden by the CDK dialog (see [cdk/dialog/dialog-container.ts#L62](https://github.com/angular/components/blob/main/src/cdk/dialog/dialog-container.ts#L62))
> fix(angular/dialog): aria-modal not being set

- src/angular/styles/_typography.scss
Adds an 0.5 opacity to disabled checkboxes and radio buttons in high contrast mode
> fix(angular/checkbox): disabled state not distinguishable in high contrast mode

- WORKSPACE
- angular-tsconfig.json
- package.json
- renovate.json
- tools/angular/BUILD.bazel
- tools/angular/esbuild.config.mjs
- tools/angular/index.bzl
- tools/defaults.bzl
- yarn.lock
The dev-infra-private packages were split to decouple the ng-dev tool from the build tooling. This allows to easily update ng-dev e.g. in LTS branches without needing to update Bazel.
It is important that ng-dev can be updated as much as possible in all branches to ensure the release IPC reliably works.
> build: account for new dev-infra packages @angular/ng-dev and `@angular/build-tooling`

- src/angular/lightbox/lightbox-container.ts
- src/angular/lightbox/lightbox.scss
- src/angular/lightbox/lightbox.spec.ts
- src/angular/lightbox/lightbox.ts
For inexplicable reasons updating the height of the Lightbox using host binding did sometimes not work. This probably has to do with the change detection of the `CdkOverlay`. In this fix we therefore update the overlay size directly using `CdkOverlay.updateSize()`.
For backward compatibility and if no `ViewportRuler` is injected, we set the initial overlay height to `100vh`.
Closes #1696
> fix(angular/lightbox): update height on window resize

- .github/actions/yarn-install/action.yml
- .github/workflows/maintenance-changelog.yml
- .github/workflows/maintenance-cherry-pick.yml
- .github/workflows/release.yml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> build: migrate GitHub Actions set-output to $GITHUB_OUTPUT

- src/angular/tooltip/tooltip.spec.ts
- src/angular/tooltip/tooltip.ts
After the tooltips were switched to CSS animations, a regression was introduced where the opposite animation is shown even if the tooltip didn't actually reach its target state.
> fix(angular/tooltip): animations running when timeouts haven't elapsed

- src/angular/tooltip/tooltip-wrapper.html
- src/angular/tooltip/tooltip-wrapper.spec.ts
- src/angular/tooltip/tooltip-wrapper.ts
BREAKING CHANGE: We align the default tooltip icon with the SBB style guide and replace the question mark with an info icon.
Closes #1684
> fix(angular/tooltip): change tooltip icon to info

- src/angular/select/select.spec.ts
- src/angular/select/select.ts
Implement page up and down functionality for select:
* Page-Down focuses the last element in the select
* Page-Up focus the first element in the select
* It's done in open and closed state
> feat(angular/select): add page down/up button functionality

- renovate.json
Renovate's postUpgradeTasks don't work anymore because of a failing postInstall script. To avoid this we run `yarn install` with `--ignore-scripts`.
> ci: don't run scripts in renovate's postUpgradeTasks

- renovate.json
`psstUpgradeTasks` using `yarn` stopped working if `skipInstalls` is set to `true`.
Maybe caused by https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/npm/post-update/lerna.ts#L63
> ci: fix renovate by setting `skipInstalls` to `false`

- src/angular/menu/menu-trigger.ts
- src/angular/menu/menu.spec.ts
In the context of a submenu trigger it is useful for a screen reader user to know whether a submenu is open or closed. By specifying the `aria-expanded` attribute as either true or false it provides an additional "collapsed" announcement to the user informing them of the state of the menu trigger when closed.
> fix(angular/menu): explicitly set aria-expanded to true/false

- src/angular/autocomplete/autocomplete-trigger.ts
In autocomplete-trigger.ts, add `| null` to the typing of optionally injected properties. This improves code health because the compiler can detect possible type errors with `null`.
> refactor(angular/autocomplete): declare injected properties as nullable

- .github/workflows/maintenance-changelog.yml
Remove `branch` workflow event. Otherwise, the workflow will trigger on every push on a release branch (workflow events are combined with `or`).
> ci: fix maintenance workflow

- renovate.json
- pin major version of node
- ignore "rollup", "@rollup/plugin-commonjs" and "@rollup/plugin-node-resolve" (updated together with @angular/bazel)
> chore(deps): update renovate.json

- src/angular/dialog/dialog.scss
If no dialog height is specified, the  content was not scrollable and the dialog footer sometimes was not visible. This is because flexbox uses `min-height: auto` by default. To make the dialog content scrollable again, the `min-height` is set to zero.
Closes #1803
> fix(angular/dialog): scrollable content if no dialog height is defined

- packages.bzl
This reverses a change from #1805 that caused the NPM package to not be published.
> ci: fix publishing of npm package

- src/journey-maps/angular/style/_functions.scss
> fix(journey-maps): display focused controls

- src/angular/oauth/resource-access.spec.ts
- src/angular/oauth/resource-access.ts
Hello
Currently, the parsing of access tokens does not quite work. Unicode characters can generate problems.
Even so far to produce an error when calling `atob` which leads to the token not being able to be parsed at all.
This PR will address that. The logic to do that is mainly taken from https://stackoverflow.com/a/38552302 
Thanks
> fix(oauth): parse token correctly to be able to parse unicode characters

- src/angular/core/option/option.ts
- src/angular/select/select.spec.ts
For sbb-option, set `aria-selected="false"` on deselected options. Confirms with [WAI ARIA Listbox authoring practices guide](https://www.w3.org/WAI/ARIA/apg/patterns/listbox/), which says to always include aria-selected attribute on listbox options that can be selected. Fix issue where VoiceOver reads every option as "selected".
> fix(angular/core): sbb-option sets aria-selected="false"

- src/angular/datepicker/datepicker/datepicker.spec.ts
- src/angular/datepicker/datepicker/datepicker.ts
- src/angular/datepicker/month-view/month-view.spec.ts
If the date of the main datepicker changes, the arrow keys of the connected datepicker need to be updated.
Closes #1852
> fix(angular/datepicker): update arrow keys of connected datepicker 

- src/angular/datepicker/datepicker-content/datepicker-content.scss
- src/angular/datepicker/datepicker/datepicker.ts
If the screen is too small to show the calendar above or below the date input, display it centered and remove the arrow pointing to the input.
Closes #1819
> fix(angular/datepicker): avoid calendar being cut off on small screens

- package.json
Fix build by adding `@babel/plugin-proposal-async-generator-functions` as a dev dependency. It's needed by `@angular/build-tooling`.
> build: fix build dependencies

- src/journey-maps/web-component/BUILD.bazel
- src/showcase/BUILD.bazel
This is necessary to avoid linting errors when updating bazel to v6.1.0.
> build: lint BUILD.bazel files

- src/angular/datepicker/calendar-body/calendar-body.html
Fixes that we had divs as children of buttons which some a11y tools complain about.
> fix(angular/datepicker): remove div as a child of button

- src/angular/header-lean/header.scss
Some INT environments are called "inte" instead of "int"; add a corresponding style class.
> feat(sbb-header-environment): add 'inte' as a recognized environment

- src/angular/tabs/tabs.md
> docs(angular/tabs): add note when using together with `routerLink`

- src/angular/autocomplete/autocomplete-trigger.ts
- src/angular/autocomplete/autocomplete.spec.ts
- src/angular/core/option/option.ts
Fixes that the selected state was lingering on the selected option even after the input value is cleared.
> fix(angular/autocomplete): clear selected option if input is cleared

- src/angular/radio-button/BUILD.bazel
- src/angular/radio-button/radio-button.spec.ts
- src/angular/radio-button/radio-button.ts
- src/angular/toggle/toggle.ts
In  a previous commit the radio group was changed so that deselected buttons receive `tabindex="-1"` when there's a selected button. The problem is that we weren't clearing the reference to the selected button so it gets removed, the deselected buttons become unfocusable using the keyboard.
These changes clear the selected radio button on destroy.
> fix(angular/radio): clear selected radio button from group

- src/angular/autocomplete/autocomplete-trigger.ts
- src/angular/autocomplete/autocomplete.spec.ts
- src/angular/autocomplete/autocomplete.ts
- src/components-examples/angular/autocomplete/autocomplete-require-selection/autocomplete-require-selection-example.html
- src/components-examples/angular/autocomplete/autocomplete-require-selection/autocomplete-require-selection-example.ts
- src/components-examples/angular/autocomplete/index.ts
Adds the `requireSelection` input to the autocomplete, which when enabled will clear the input value if the user doesn't select an option from the list.
> feat(angular/autocomplete): add input to require selection from the panel

- src/angular/accordion/accordion-animations.ts
The accordion was setting `visibility: visible` on the content which meant that it would be visible when placed inside of a parent that is `visibility: hidden`.
These changes resolve the issue by clear the `visibility` instead.
> fix(angular/accordion): content visible when placed inside a hidden parent

- src/angular/header-lean/header-directives.ts
- src/angular/header-lean/header-lean.md
- src/angular/header-lean/header.html
- src/angular/header-lean/header.module.ts
- src/angular/header-lean/header.scss
- src/angular/header-lean/header.spec.ts
- src/angular/schematics/ng-update/migrations/sbb-angular-symbols.json
Adds the `<sbb-header-icon-actions />` directive for displaying icon buttons on the right side of the header, left to the `<sbb-usermenu>` and the `[brand]` element.
Closes #902
> feat(angular/header-lean): add directive to display icon buttons in header

- src/angular/dialog/dialog-container.ts
- src/angular/dialog/dialog-content-directives.ts
- src/angular/dialog/dialog.spec.ts
- src/angular/lightbox/lightbox-container.ts
Currently the dialog assigns the ID of the title as the `aria-labelleledby` of the container, but it doesn't update it if the title is swapped out or removed.
These changes add a queue of possible IDs that the container can use as titles are being created or destroyed.
> fix(angular/dialog): update aria-labelledby if title is swapped

- src/angular/tabs/tab-group.html
- src/angular/tabs/tab-group.spec.ts
Fix accessibility for tabs component. Add `aria-hidden="true"` to inactive tab panels. Fix issue where chromevox would read the names of inactive tab panels when navigating past the active tab panel. Fix this by adding `aria-hidden="true"` to inactive tab panels to exclude them from the a11y tree.
> fix(angular/tabs):  add aria-hidden to inactive tabs

- src/angular/table/table/row.ts
- src/angular/table/table/table.ts
The SBB Angular table had a few places where it was importing a component's template as a string. This is incompatible with the upcoming local compilation mode in the compiler. These changes inline the templates instead.
> fix(angular/table): resolve local compilation issues

- src/angular/styles/_typography.scss
Although the button should only be used in standard variant, there should be a suitable color for dark mode. This pr changes the color to aluminium in dark mode.
> fix(angular/button): dark mode style for frameless button

- src/angular/tabs/tab-nav-bar.spec.ts
- src/angular/tabs/tab-nav-bar.ts
Fixes that the tab nav bar wasn't navigating when pressing the enter key.
> fix(angular/tabs): nav bar not navigating on enter presses

- src/angular/core/common-behaviors/common.module.ts
- src/angular/core/common-behaviors/variant.ts
- src/angular/notification/notification.html
- src/angular/styles/_typography.scss
- src/angular/typography.md
- src/showcase/app/app.component.html
- src/showcase/app/app.component.ts
- src/showcase/app/variant-switch.ts
- src/showcase/styles.scss
This removes the newly introduced `lean_dark` variant. Instead, if the system's preferred color scheme is dark, the dark mode is applied automatically for the lean design variant.
The default behavior can be overridden by adding the `sbb-light` or `sbb-dark` class to the page's `<html>` element.
> refactor: autodetect dark mode

- src/angular/styles/_typography.scss
In my last pr I changed the color of disabled selection containers to fix the radio button disabled style. This broke the checkbox. This pr now fixes the disabled style for both, radio button and checkbox.
> chore: fix disabled radio button and checkbox style

- src/angular/styles/_typography.scss
Change border color of input elements to smoke to be wcag 2.2 conform. This changes the color in lean and standard mode.
> fix(angular/input): change border color to smoke

- src/angular/styles/_typography.scss
Change sidebar background color from midnight to charcoal to match design specification.
> fix(angular/sidebar): change dark mode background to charcoal

- src/components-examples/angular/table/expandable-table/expandable-table-example.html
Not all browsers support `visibility: collapse` on table rows. Some browsers, e.g. Safari, treat it like `visibility: hidden` which causes a gap below the clickable rows. Therefore, rows are now hidden using `display: none` and shown using `display: table-row` what is supported by all major browsers.
See https://developer.mozilla.org/en-US/docs/Web/CSS/display and https://developer.mozilla.org/en-US/docs/Web/CSS/visibility
Closes #2100
> fix(showcase): make expandable table example working on all browsers

- src/angular/sidebar/sidebar/sidebar.scss
- src/angular/styles/_typography.scss
Use a darker color for sidebar items on hover than for menu items. This is necessary because the sidebar has a lighter background in dark mode than the menu.
> fix(angular/sidebar): darker hover color for sidebar items in dark mode

- src/components-examples/journey-maps/angular/journey-maps-full/journey-maps-full-example.html
- src/components-examples/journey-maps/angular/journey-maps-full/journey-maps-full-example.ts
- src/journey-maps/angular/journey-maps.interfaces.ts
- src/journey-maps/web-component/showcase.ts
> feat(journey-maps): new POIs category p2p_car_sharing

- src/angular/tag/tag.scss
The `SbbTag`, which inherits from the `SbbCheckbox`, stayed focussed until the user clicked somewhere else. This PR fixes this and removes the visible focus on blur leaving the element focussed in the background for not breaking keyboard navigation. Only tags focussed using keyboard navigation remain focussed.
Fixes #2119
> fix(angular/tags): remove focus on mouse blur

- src/journey-maps/angular/components/level-switch/level-switch-horizontal.scss
- src/journey-maps/angular/style/_functions.scss
example warning
```
DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div(v.$controlsWidthSmall, 2) or calc(v.$controlsWidthSmall / 2)
More info and automated migrator: https://sass-lang.com/d/slash-div
╷
101 │       width: v.$controlsWidthSmall / 2;
│              ^^^^^^^^^^^^^^^^^^^^^^^^^
```
> build: resolve deprecation warning during build

- package.json
- src/showcase/assets/stack-blitz/package-lock.json
- src/showcase/assets/stack-blitz/package.json
Increase the default library version to 17.4.1 and CDK to 17.1.0 because older versions are not compatible.
> fix(stackblitz): update stackblitz assets

- src/angular/badge/BUILD.bazel
- src/angular/badge/badge.ts
- src/angular/button/BUILD.bazel
- src/angular/button/button.ts
- src/angular/chips/BUILD.bazel
- src/angular/chips/chip.ts
- src/angular/sidebar/BUILD.bazel
- src/angular/sidebar/sidebar/sidebar.ts
- src/angular/tabs/BUILD.bazel
- src/angular/tabs/paginated-tab-header.ts
- src/angular/tabs/tab-group.ts
- src/angular/tabs/tab-header.ts
- src/angular/tabs/tab-nav-bar.ts
- src/angular/tooltip/BUILD.bazel
- src/angular/tooltip/tooltip.ts
- tools/defaults.bzl
Moves all imports of `ANIMATION_MODULE_TYPE` from `platform-browser/animations` to `core` to reduce our dependence on the animations module and to avoid potential issues when lazy-loading animations.
> fix(multiple): import ANIMATION_MODULE_TYPE from core

- src/angular/checkbox/checkbox-required-validator.ts
- src/angular/checkbox/checkbox.module.ts
- src/angular/checkbox/checkbox.ts
Currently, required validation is implemented as a separate directive. This is problematic, because with standalone users would have to add two imports.
These changes move the required validation into the checkbox and deprecate the old module.
> fix(angular/checkbox): move required validation into component

- src/angular/chips/chip-list.ts
- src/angular/core/common-behaviors/error-state.ts
- src/angular/i18n/xlf/messages.xlf
- src/angular/i18n/xlf2/messages.xlf
- src/angular/input/input.ts
- src/angular/schematics/ng-update/migrations/sbb-angular-symbols.json
- src/angular/select/select.ts
- src/angular/textarea/textarea/textarea.ts
Extract error tracking behavior into a class and remove TypeScript mixin usages. The `mixinErrorState` is marked as deprecated.
> refactor(multiple): extract error tracking behavior into a class

- src/angular/dialog/dialog-ref.ts
Const enums prevent enabling the `isolatedModules` check which is needed for fast TS compilation based on transpileModule API.
> refactor(angular/dialog): use enum instead of const enum

- src/angular/autocomplete/autocomplete-trigger.ts
- src/angular/autocomplete/autocomplete.spec.ts
Clears the selected option in the autocomplete if the user types in something else.
This also fixes a regression #2010 where the call to capture the input value was moved into the root of `_attachOverlay` in order to capture it even when there are no options. This is problematic, because `_attachOverlay` is called as the user is typing which basically breaks the `requireSelection` feature.
These changes resolve the issue while preserving the original fix by only capturing the value when the overlay is actually attached.
> fix(angular/autocomplete): clear selected option if it is removed while typing

- src/angular/styles/_typography.scss
When opening a menu, the first item was always displayed in a focused state. The focus could only be removed using keyboard navigation or by clicking somewhere else.
This fix keeps the item focused in the background. However, the item is only displayed in a focused state if it was focused using keyboard navigation.
Fixes #2105
> fix(angular/menu): don't visually focus first item if menu is opened

- src/angular/tabs/tab-nav-bar.spec.ts
- src/angular/tabs/tab-nav-bar.ts
Fixes that while we were preventing clicks on disabled links using `pointer-events`, we didn't prevent keyboard events.
Moreover, scrolling when hitting space is prevented.
> fix(angular/tabs): prevent scrolling and disable interaction if disabled

- .github/Dockerfile.regenerate
- .github/workflows/regenerate-images.yml
- .github/workflows/release.yml
This should prevent security issues from accumulating in the images, as they are continuously regenerated from the newest nginx stable image.
> build: add workflow to regenerate images of latest major versions

- src/angular/input/input.spec.ts
- src/angular/input/input.ts
Fixes that the `tabIndex` attribute set on an `SbbInput` was swallowed by the component.
Fixes #2203
> fix(angular/input): don't swallow the tabIndex

- src/angular/core/common-behaviors/initialized.ts
- src/angular/i18n/xlf/messages.xlf
- src/angular/i18n/xlf2/messages.xlf
- src/angular/pagination/BUILD.bazel
- src/angular/pagination/paginator/paginator.ts
- src/angular/table/sort/sort.ts
This removes the usage of `mixinInitialized` and marks it as deprecated
> refactor(multiple): remove TypeScript mixin usage

- src/angular/autocomplete/autocomplete-trigger.ts
- src/angular/autocomplete/autocomplete.spec.ts
Fixes that if the user has `requireSelection` enabled, selects a value and then deletes a character while the input still has a value, the selection wasn't being cleared as expected.
> fix(angular/autocomplete): requireSelection sometimes not clearing value

- src/angular/core/common-behaviors/error-state.ts
Updates fields on `HasErrorState` to be nullable to align them with the `_ErrorStateTracker`.
> fix(angular/core): mark fields on HasErrorState as nullable

- src/angular/core/common-behaviors/disabled.ts
- src/angular/core/common-behaviors/error-state.ts
- src/angular/core/common-behaviors/initialized.ts
- src/angular/core/common-behaviors/tabindex.ts
- src/angular/sidebar/sidebar-base.ts
Give the consumers a bit more time. These deprecations are only a few weeks old.
> chore: adjust deprecation target version

- src/angular/tabs/paginated-tab-header.ts
- src/angular/tabs/tab-header.spec.ts
- tslint.json
This reverts commit fbc4f97d70954acd62cf8b11bf8b2d4a7db7ac53.
This is currently breaking the app due to compilation issues. I'll create a PR with this changes for further investigation.
> Revert "fix(angular/tabs): use ResizeObserver to react to size changes (#2234)"

- src/angular/file-selector/file-selector.html
- src/angular/file-selector/file-selector.spec.ts
This fixes a bug where the `SbbFileSelector` can only be used in "multiple" mode. By removing the `multiple` attribute on the underlying input field if `multiple` is set to `false` on the component, single selection is now working.
Fixes #2238
> fix(angular/file-selector): allow disabling multiple mode

- src/angular/badge/badge.md
- src/angular/styles/_typography.scss
- src/components-examples/angular/badge/BUILD.bazel
- src/components-examples/angular/badge/badge-overview/badge-overview-example.html
- src/components-examples/angular/badge/badge-overview/badge-overview-example.ts
This fixes the positioning of badges on icons. Since I couldn't find any cases where the badge was positioned "above" on an icon, I would not consider this fix as a breaking change.
Fixes #2225
> fix(angular/badge): fix badge positioning on icon

- src/angular/form-field/form-field-control.ts
- src/angular/form-field/form-field.html
- src/angular/select/select.ts
- src/angular/textarea/textarea/textarea.ts
Adds an option to remove the `for` attribute from the `<label>` inside the form field from elements that can't be labeled. Also applies the new option to `sbb-select` and `sbb-textarea`. This isn't an accessibility regression, because those elements were already being labeled using `aria-labelledby`. Fixes #1918
> fix(multiple): remove label for attribute on non-native elements

- src/angular/dialog/dialog-content-directives.ts
- src/angular/dialog/dialog.spec.ts
- src/angular/i18n/xlf/messages.xlf
- src/angular/i18n/xlf2/messages.xlf
Adds `CdkScrollable` to `SbbDialogContent` so that overlays inside of it can reposition on scroll.
> fix(angular/dialog): mark dialog content as scrollable

- src/angular/menu/menu.html
- src/angular/menu/menu.ts
We can set classes directly through `[class]` instead of having to import `NgClass`. The code had to be adjusted a bit, because the built-in `[class]` binding doesn't do diffing on the object literal.
> fix(angular/menu): remove dependency on NgClass

- src/angular/autocomplete/autocomplete.html
- src/angular/autocomplete/autocomplete.ts
We can set classes directly through `[class]` instead of having to import `NgClass`.
> fix(angular/autocomplete): remove dependency on NgClass

- src/angular/datepicker/calendar-body/calendar-body.html
- src/angular/datepicker/calendar-body/calendar-body.ts
- src/angular/datepicker/datepicker-content/datepicker-content.html
- src/angular/datepicker/datepicker-content/datepicker-content.ts
- src/angular/datepicker/datepicker/datepicker.ts
We can set classes directly through `[class]` instead of having to import `NgClass`.
> fix(angular/datepicker): remove dependency on NgClass

- src/angular/tooltip/tooltip.ts
This commit fixes an error in the tooltip component where it updates a value used in a host binding without calling `markForCheck`. This does not currently throw an error because `checkNoChanges` is broken for `OnPush` components. However, the error was surfaced when testing an "exhaustive" check that will check _all_ views, regardless of their dirty state. The issue also doesn't really produce a _visible_ problem because it occurs when the tooltip is hidden so the fact that the zoom never updates doesn't make a real difference.
> fix(angular/tooltip): tooltip should mark for check when visibility changes

- src/angular/chips/chip-input.ts
- src/angular/chips/chip-list.spec.ts
- src/angular/chips/chip.ts
We have some logic that prevents chip removal if the users is holding down the backspace key. It currently breaks down in the case where a value is pasted into the input via click.
These changes simplify our detection by using `KeyboardEvent.repeat` which also resolves the paste issue.
> fix(angular/chips): simplify repeat chip removal prevention

- src/angular/datepicker/calendar-body/calendar-body.html
- src/angular/datepicker/calendar-body/calendar-body.ts
- src/angular/datepicker/month-view/month-view.html
Fixes that the calendar was triggering some newly-introduced warnings from the framework.
> fix(angular/datepicker): resolve repeater warnings in calendar

- RELEASE.md
- src/angular/schematics/migration.json
- src/angular/schematics/ng-update/index.ts
Updating SBB-Angular to v18 using the recommended `ng update` did not work because the schematic function was not updated. This PR fixes the update schematics.
> fix: update schematics for v18

- src/angular/accordion/expansion-panel.scss
- src/angular/i18n/xlf/messages.xlf
- src/angular/i18n/xlf2/messages.xlf
- src/angular/sidebar/sidebar.md
- src/angular/sidebar/sidebar/sidebar-container.html
- src/angular/sidebar/sidebar/sidebar.html
- src/angular/sidebar/sidebar/sidebar.scss
- src/angular/sidebar/sidebar/sidebar.spec.ts
- src/angular/sidebar/sidebar/sidebar.ts
- src/angular/styles/_mixins.scss
- src/angular/styles/_typography.scss
- src/components-examples/angular/sidebar/BUILD.bazel
- src/components-examples/angular/sidebar/collapsible-sidebar/collapsible-sidebar-example.css
- src/components-examples/angular/sidebar/collapsible-sidebar/collapsible-sidebar-example.html
- src/components-examples/angular/sidebar/collapsible-sidebar/collapsible-sidebar-example.ts
- src/components-examples/angular/sidebar/index.ts
This allows to make the `SbbSidebar` collapsible. If collapsible, the sidebar is displayed in `over` mode (above the content) and can be closed by clicking the close button. The `toggleSidebar()` method can be used to open or collapse the sidebar.
Closes #2263
> feat(angular/sidebar): make sidebar collapsible

- src/angular/dialog/dialog.ts
This provides the dialog service in root and adds deprecations to unused injection tokens.
> fix(angular/dialog): provide dialog service in root

- src/angular/i18n/xlf/messages.xlf
- src/angular/i18n/xlf2/messages.xlf
- src/angular/sidebar/sidebar/sidebar.ts
Fixes that the sidebar wasn't triggering change detection when closing via escape key press.
> fix(angular/sidebar): not closing on escape key press

- src/angular/breadcrumb/breadcrumbs.ts
- src/angular/chips/chip-list.spec.ts
- src/angular/chips/chip-list.ts
- src/angular/chips/chip-remove.spec.ts
- src/angular/chips/chip.ts
- src/angular/i18n/xlf/messages.xlf
- src/angular/i18n/xlf2/messages.xlf
- src/angular/radio-button-panel/radio-button-panel.spec.ts
- src/angular/radio-button/radio-button.spec.ts
- src/angular/select/select.spec.ts
- src/angular/sidebar/icon-sidebar/icon-sidebar.spec.ts
- src/angular/sidebar/sidebar/sidebar.spec.ts
- src/angular/sidebar/sidebar/sidebar.ts
- src/angular/table/sort/sort.spec.ts
- src/angular/table/table.spec.ts
- src/angular/tabs/tab-body.spec.ts
- src/angular/tabs/tab-body.ts
- src/angular/tabs/tab-group.spec.ts
- src/angular/tabs/tab-header.spec.ts
- src/angular/tabs/tab-nav-bar.spec.ts
- src/angular/tag/tags.spec.ts
- src/angular/textarea/textarea/textarea.spec.ts
- src/angular/time-input/time-input.spec.ts
- src/angular/tooltip/tooltip-wrapper.spec.ts
- src/angular/tooltip/tooltip.spec.ts
- src/angular/tooltip/tooltip.zone.spec.ts
- src/angular/usermenu/usermenu.spec.ts
- test/angular-test-init-spec.ts
- tslint.json
Convert remaining tests to zoneless change detection and use zoneless by default for tests. For testing functionality to work with zoneless change detection, move the test to a `*.zone.spec.ts` file.
> test: convert remaining tests to zoneless change detection

- src/angular/datepicker/calendar/calendar.ts
When some calendar inputs change, we need to re-render the entire view (e.g. `minDate` or `dateFilter`). This can cause the active cell to lose focus since it's being re-rendered.
These changes schedule the active cell to be re-focused in the cases where the view would be re-rendered.
> fix(angular/datepicker): avoid losing focus when re-rendering the current view

- src/angular/tabs/paginated-tab-header.ts
This reverts commit 0f67f0ce7493215b1fdd40c511953bf07a749c62.
Undoing, because this breaks the Showcase. I'll investigate it later.
> Revert "fix(angular/tabs): use ResizeObserver to react to size changes

- src/angular/i18n/xlf/messages.xlf
- src/angular/i18n/xlf2/messages.xlf
- src/angular/sidebar/sidebar.md
- src/angular/sidebar/sidebar/sidebar.spec.ts
- src/angular/sidebar/sidebar/sidebar.ts
This adds the `opened` input property to control the open state of the sidebar. If `opened` is set, the sidebar is not toggled automatically if the mobile state changes.
Closes #2360
> feat(angular/sidebar): allow controlling the opened state of the sidebar

- src/journey-maps/angular/services/map/map-poi-service.ts
Fix: by default all 2nd-level POI (-categories) in the new V3 style should be visible
> fix(journey-maps): changed POI V3 style default visibility to visible

- src/angular/checkbox/checkbox.html
- src/angular/checkbox/checkbox.md
- src/angular/checkbox/checkbox.spec.ts
- src/angular/checkbox/checkbox.ts
Added three new aria properties to SbbCheckbox:
`aria-expanded`: Indicates whether the checkbox controls the visibility of another element. This should be a boolean value (true or false). `aria-controls`: Specifies the ID of the element that the checkbox controls. `aria-owns`: Specifies the ID of the element that the checkbox visually owns.
These attributes will be added to the generated checkbox element if they are specified and won't be present in the HTML if not provided.
> feat(angular/checkbox): add new aria properties to SbbCheckbox

- src/angular/select/select.spec.ts
- src/angular/select/select.ts
Fixes a bug where the usage of aria-autocomplete is not a valid attribute that can be used with aria role=listbox. Removes the aria-autocomplete attribute to fix the violation: aria-allowed-attr.
> fix(angular/select): remove incompatible aria-autocomplete attribute

- src/angular/input/input-value-accessor.ts
- src/angular/input/input.ts
Expands the `SBB_INPUT_VALUE_ACCESSOR` to support a signal-based accessor.
> refactor(angular/input): support signal-based input accessor

- src/angular/form-field/form-field.scss
Fixes the size of the tooltip icon if it's placed inside an `<sbb-label />` that's not wrapped by an `<sbb-form-field />`.
Example before this change:
> fix(angular/tooltip): correct icon styling when placed inside label

- package.json
- src/angular/table/table.spec.ts
- yarn.lock
Fix table tests after Angular CDK update. These changes are necessary because the Angular CDK now uses the ResizeObserver for updating sticky columns.
See https://github.com/angular/components/commit/8c52b6d8f14516db3873b6626902ffdf348c006a
> test(angular/table): fix table tests after CDK update

- src/angular/tabs/tab-body.ts
Removes a workaround that's no longer necessary now that we don't support IE.
> fix(angular/tabs): remove IE animation workaround

- src/angular/accordion/accordion.module.ts
- src/angular/autocomplete/autocomplete.module.ts
- src/angular/button/button.module.ts
- src/angular/datepicker/datepicker.module.ts
- src/angular/header-lean/header.module.ts
- src/angular/menu/menu.module.ts
- src/angular/notification/notification.module.ts
- src/angular/processflow/processflow.module.ts
- src/angular/search/search.module.ts
- src/angular/select/select.module.ts
- src/angular/status/status.module.ts
- src/angular/tag/tag.module.ts
- src/angular/toggle/toggle.spec.ts
- src/angular/tooltip/tooltip.module.ts
- src/angular/usermenu/usermenu.module.ts
- src/showcase/app/angular/angular.module.ts
- src/showcase/app/shared/shared.module.ts
Removes all our imports of `CommonModule` since it wasn't being used for anything.
> refactor(multiple): remove CommonModule imports

- src/angular/i18n/xlf/messages.xlf
- src/angular/i18n/xlf2/messages.xlf
- src/angular/sidebar/sidebar/sidebar.ts
Removes a workaround that's no longer necessary now that we don't support IE.
> fix(angular/sidebar): remove IE animation workaround

- package.json
- src/components-examples/journey-maps/angular/journey-maps-basic/journey-maps-basic-example.css
- src/components-examples/journey-maps/angular/journey-maps-map-navigation/journey-maps-map-navigation-example.css
- src/components-examples/journey-maps/angular/journey-maps-pois-markers/journey-maps-pois-markers-example.css
- src/components-examples/journey-maps/angular/journey-maps-routes-zones/journey-maps-routes-zones-example.css
- src/components-examples/journey-maps/angular/journey-maps-style-options/journey-maps-style-options-example.css
- src/components-examples/journey-maps/angular/journey-maps-ui-options/journey-maps-ui-options-example.css
- src/components-examples/journey-maps/esri-plugin/esri-plugin/esri-plugin-example.css
- src/journey-maps/angular/angular.md
- src/journey-maps/angular/services/map/map-marker-service.ts
- src/journey-maps/angular/services/map/map-service.ts
- src/journey-maps/esri-plugin/esri-plugin.md
- src/journey-maps/package.json
- src/showcase/app/shared/shared.module.ts
- src/showcase/assets/stack-blitz/package.json
- yarn.lock
> chore(journey-maps): upgrade maplibre to 4.7.1

- src/angular/form-field/form-field.ts
Currently we set the `aria-describedby` every time the state of the form control changes. This is excessive, because it only needs to happen if the error state or `userAriaDescribedBy` change.
> fix(angular/form-field): avoid touching the DOM on each state change

- src/angular/menu/menu-trigger.ts
- src/angular/menu/menu.html
- src/angular/menu/menu.spec.ts
- src/angular/menu/menu.ts
Currently `sbb-menu` handles its keyboard events in the template, however this ignores the overlay's stacking context which can capture some events that it shouldn't.
These changes switch the menu to handling the events through the common dispatcher instead.
> fix(angular/menu): handle keyboard events through dispatcher

- src/angular/dialog/dialog-config.ts
- src/angular/lightbox/lightbox-config.ts
- src/angular/menu/menu-content.ts
- src/angular/tabs/BUILD.bazel
- src/angular/tabs/tab-body.ts
Removes the final places where we were referring to `ComponentFactoryResolver` in our SBB Angular code.
> fix(angular): remove final references to ComponentFactoryResolver

- .github/workflows/preview-deployment.yml
The call to `github.rest.repos.createDeployment()` fails if any required commit status checks do not have a "success" state (e.g., when "preview-deployment" has a "skipped" state). This change ensures that only relevant contexts are considered, ignoring the others.
> build: fix preview deployment

- src/angular/select/select.spec.ts
- src/angular/select/select.ts
- src/components-examples/angular/select/index.ts
- src/components-examples/angular/select/select-selectable-null/select-selectable-null-example.html
- src/components-examples/angular/select/select-selectable-null/select-selectable-null-example.ts
By default, `sbb-select` treats options with nullable values as "reset options", meaning that they can't be selected, but rather they clear the select's value. This behavior is based on how the native `select` works, however in some cases it's not desirable. These changes add an input that users can use to opt out of the default behavior.
> fix(angular/select): add opt-in input that allows selection of nullable options

- src/angular/accordion/expansion-panel.html
- src/angular/accordion/expansion-panel.ts
Currently, the expansion panel prevents focus from entering it using `visibility: hidden`, but that only works when it's closed. This means that if the user tabs into it while it's animating, they may scroll the content make the component look broken.
These changes resolve the issue by setting `inert` on the panel content while it's animating. Also cleans up an old workaround for IE.
> fix(angular/accordion): prevent focus from entering the panel while it's animating

- src/angular/accordion/accordion-animations.ts
- src/angular/accordion/expansion-panel-header.html
- src/angular/accordion/expansion-panel-header.ts
- src/angular/accordion/expansion-panel.html
- src/angular/accordion/expansion-panel.scss
- src/angular/accordion/expansion-panel.spec.ts
- src/angular/accordion/expansion-panel.ts
Reworks the accordion to animate purely with CSS, rather than going through the `@angular/animations` module to simplify the setup.
Fixes #2055
> fix(angular/accordion): switch away from animations module

- .github/workflows/continuous-integration.yml
The Chrome browser used by bazel stopped working after Ubuntu was updated to 24. Therefore, we temporarily downgrade to Ubuntu 22.
> test: fix tests by running them on Ubuntu 22

- src/angular/i18n/xlf/messages.xlf
- src/angular/i18n/xlf2/messages.xlf
- src/angular/sidebar/sidebar/sidebar-animations.ts
- src/angular/sidebar/sidebar/sidebar.scss
- src/angular/sidebar/sidebar/sidebar.spec.ts
- src/angular/sidebar/sidebar/sidebar.ts
Reworks the sidevar to animate using CSS, rather than the animations module. This requires less JavaScript, is simpler to maintain and avoids some memory leaks caused by the animations module.
> fix(angular/sidebar): switch away from animations module

- src/angular/styles/_typography.scss
- src/components-examples/angular/input/input-form/input-form-example.html
For accessibility reasons, we want to show the spin buttons in `input[type='number']`
Closes #2380
> fix(angular/input): show spin buttons for number input

- .github/Dockerfile.regenerate
- .github/Dockerfile.regenerate.ngssc
- .github/actions/setup-mint/action.yml
- .github/workflows/regenerate-images.yml
- scripts/find-major-versions.sh
- scripts/regenerate-image.sh
This PR optimizes the scripts/workflow for regenerating the images. It also uses mint to minify the images.
> build: refactor image regeneration

- src/angular/accordion/expansion-panel.ts
- src/angular/autocomplete/autocomplete-trigger.ts
- src/angular/button/button.ts
- src/angular/header-lean/header-menu-trigger.ts
- src/angular/input/input.ts
- src/angular/menu/menu-trigger.ts
- src/angular/tooltip/tooltip.ts
Switches our manual calls into `addEventListener` to use the renderer instead so that tooling (e.g. the tracing service) gets notified about them.
> refactor(multiple): use renderer for manual event bindings

- test/angular-test.init.ts
Otherwise, tests will fail because of NG0914 warning.
> test: use correct import order in angular-test.init.ts

- src/angular/dialog/dialog.module.ts
- src/angular/dialog/dialog.ts
Removes the deprecated symbols for v20 from the checkbox.
* `SBB_DIALOG_SCROLL_STRATEGY_FACTORY` has been removed.
* `SBB_DIALOG_SCROLL_STRATEGY_PROVIDER_FACTORY` has been removed.
* `SBB_DIALOG_SCROLL_STRATEGY_PROVIDER` has been removed.
> fix(angular/dialog): breaking changes for v20

- src/angular/lightbox/lightbox.module.ts
- src/angular/lightbox/lightbox.ts
Removes the deprecated symbols for v20 from the lightbox.
* `SBB_LIGHTBOX_SCROLL_STRATEGY_FACTORY` has been removed.
* `SBB_LIGHTBOX_SCROLL_STRATEGY_PROVIDER_FACTORY` has been removed.
* `SBB_LIGHTBOX_SCROLL_STRATEGY_PROVIDER` has been removed.
> fix(angular/lightbox): breaking changes for v20

- src/angular/autocomplete/autocomplete-trigger.ts
- src/angular/autocomplete/autocomplete.spec.ts
- src/angular/select/select.spec.ts
- src/angular/select/select.ts
For Select and Autocomplete components, fix issues where VoiceOver was confused by the ARIA semantics of the combobox. Fix multiple behaviors:
Fix VoiceOver focus ring stuck on the combobox while navigating options. Fix VoiceOver would sometimes reading option as a TextNode and not communicating the selected state and position in set. Fix VoiceOver "flickering" behavior where VoiceOver would display one announcement then quickly change to another announcement. Fix the same issues for both Select and Autocomplete component.
Implement fix by correcting the combobox element and also individual options.
First, move the aria-owns reference to the overlay from the child of the combobox to the parent modal of the comobobx. Having an aria-owns reference inside the combobox element seemed to …
> fix(multiple): fix VoiceOver confused by Select/Autocomplete's ARIA semantics

- renovate.json
There's no equivalent to `--non-interactive` when using `pnpm install`.
> ci: fix renovate's post upgrade task

- renovate.json
Renovate is currently not working because it cannot access the `pnpm-workspace.yaml` file. Instead of using `includePaths`, we now use `ignorePaths` to prevent Renovate updating the stackblitz dependencies.
> ci: fix renovate

- BUILD.bazel
- MODULE.bazel
- MODULE.bazel.lock
Within our module.bazel file when describing the version of typescript to use for rules_ts, we use ts_version instead of ts_version_from to prevent our package.json file from being part of the set of files used to calculate the sha for the lock file. Any unrelated change to the version of the typescript file would end up causing our lockfile to be out of date.
> build: define typescript version via string in module.bazel file

- src/angular/autocomplete/autocomplete-trigger.ts
I wasn’t able to reproduce the issue described in the linked ticket.  
The most likely explanation is that the component gets destroyed when the `afterNextRender` callback executes.  
This change adds a check to skip the callback if the component has already been destroyed.
Fixes #2515
> fix(angular/autocomplete): don't throw NG0911 when destroyed during rendering
